// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weave/trait/telemetry/tunnel.proto

package weave.trait.telemetry.tunnel;

public final class Tunnel {
  private Tunnel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TelemetryTunnelTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.telemetry.tunnel.TelemetryTunnelTrait)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait}
   */
  public static final class TelemetryTunnelTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.telemetry.tunnel.TelemetryTunnelTrait)
      TelemetryTunnelTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TelemetryTunnelTrait.newBuilder() to construct.
    private TelemetryTunnelTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TelemetryTunnelTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TelemetryTunnelTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TelemetryTunnelTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.class, weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.Builder.class);
    }

    /**
     * Protobuf enum {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType}
     */
    public enum TunnelType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TUNNEL_TYPE_UNSPECIFIED = 0;</code>
       */
      TUNNEL_TYPE_UNSPECIFIED(0),
      /**
       * <code>TUNNEL_TYPE_NONE = 1;</code>
       */
      TUNNEL_TYPE_NONE(1),
      /**
       * <code>TUNNEL_TYPE_PRIMARY = 2;</code>
       */
      TUNNEL_TYPE_PRIMARY(2),
      /**
       * <code>TUNNEL_TYPE_BACKUP = 3;</code>
       */
      TUNNEL_TYPE_BACKUP(3),
      /**
       * <code>TUNNEL_TYPE_SHORTCUT = 4;</code>
       */
      TUNNEL_TYPE_SHORTCUT(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TUNNEL_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int TUNNEL_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>TUNNEL_TYPE_NONE = 1;</code>
       */
      public static final int TUNNEL_TYPE_NONE_VALUE = 1;
      /**
       * <code>TUNNEL_TYPE_PRIMARY = 2;</code>
       */
      public static final int TUNNEL_TYPE_PRIMARY_VALUE = 2;
      /**
       * <code>TUNNEL_TYPE_BACKUP = 3;</code>
       */
      public static final int TUNNEL_TYPE_BACKUP_VALUE = 3;
      /**
       * <code>TUNNEL_TYPE_SHORTCUT = 4;</code>
       */
      public static final int TUNNEL_TYPE_SHORTCUT_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TunnelType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TunnelType forNumber(int value) {
        switch (value) {
          case 0: return TUNNEL_TYPE_UNSPECIFIED;
          case 1: return TUNNEL_TYPE_NONE;
          case 2: return TUNNEL_TYPE_PRIMARY;
          case 3: return TUNNEL_TYPE_BACKUP;
          case 4: return TUNNEL_TYPE_SHORTCUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TunnelType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TunnelType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TunnelType>() {
              public TunnelType findValueByNumber(int number) {
                return TunnelType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.getDescriptor().getEnumTypes().get(0);
      }

      private static final TunnelType[] VALUES = values();

      public static TunnelType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TunnelType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType)
    }

    /**
     * Protobuf enum {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState}
     */
    public enum TunnelState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TUNNEL_STATE_UNSPECIFIED = 0;</code>
       */
      TUNNEL_STATE_UNSPECIFIED(0),
      /**
       * <code>TUNNEL_STATE_NO_TUNNEL = 1;</code>
       */
      TUNNEL_STATE_NO_TUNNEL(1),
      /**
       * <code>TUNNEL_STATE_PRIMARY_ESTABLISHED = 2;</code>
       */
      TUNNEL_STATE_PRIMARY_ESTABLISHED(2),
      /**
       * <code>TUNNEL_STATE_BACKUP_ONLY_ESTABLISHED = 3;</code>
       */
      TUNNEL_STATE_BACKUP_ONLY_ESTABLISHED(3),
      /**
       * <code>TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLISHED = 4;</code>
       */
      TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLISHED(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TUNNEL_STATE_UNSPECIFIED = 0;</code>
       */
      public static final int TUNNEL_STATE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>TUNNEL_STATE_NO_TUNNEL = 1;</code>
       */
      public static final int TUNNEL_STATE_NO_TUNNEL_VALUE = 1;
      /**
       * <code>TUNNEL_STATE_PRIMARY_ESTABLISHED = 2;</code>
       */
      public static final int TUNNEL_STATE_PRIMARY_ESTABLISHED_VALUE = 2;
      /**
       * <code>TUNNEL_STATE_BACKUP_ONLY_ESTABLISHED = 3;</code>
       */
      public static final int TUNNEL_STATE_BACKUP_ONLY_ESTABLISHED_VALUE = 3;
      /**
       * <code>TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLISHED = 4;</code>
       */
      public static final int TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLISHED_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TunnelState valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TunnelState forNumber(int value) {
        switch (value) {
          case 0: return TUNNEL_STATE_UNSPECIFIED;
          case 1: return TUNNEL_STATE_NO_TUNNEL;
          case 2: return TUNNEL_STATE_PRIMARY_ESTABLISHED;
          case 3: return TUNNEL_STATE_BACKUP_ONLY_ESTABLISHED;
          case 4: return TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLISHED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TunnelState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TunnelState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TunnelState>() {
              public TunnelState findValueByNumber(int number) {
                return TunnelState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.getDescriptor().getEnumTypes().get(1);
      }

      private static final TunnelState[] VALUES = values();

      public static TunnelState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TunnelState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState)
    }

    public interface TelemetryTunnelStatsEventOrBuilder extends
        // @@protoc_insertion_point(interface_extends:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string txBytesToService = 1;</code>
       * @return The txBytesToService.
       */
      java.lang.String getTxBytesToService();
      /**
       * <code>string txBytesToService = 1;</code>
       * @return The bytes for txBytesToService.
       */
      com.google.protobuf.ByteString
          getTxBytesToServiceBytes();

      /**
       * <code>string rxBytesFromService = 2;</code>
       * @return The rxBytesFromService.
       */
      java.lang.String getRxBytesFromService();
      /**
       * <code>string rxBytesFromService = 2;</code>
       * @return The bytes for rxBytesFromService.
       */
      com.google.protobuf.ByteString
          getRxBytesFromServiceBytes();

      /**
       * <code>uint32 txMessagesToService = 3;</code>
       * @return The txMessagesToService.
       */
      int getTxMessagesToService();

      /**
       * <code>uint32 rxMessagesFromService = 4;</code>
       * @return The rxMessagesFromService.
       */
      int getRxMessagesFromService();

      /**
       * <code>uint32 tunnelDownCount = 5;</code>
       * @return The tunnelDownCount.
       */
      int getTunnelDownCount();

      /**
       * <code>uint32 tunnelConnAttemptCount = 6;</code>
       * @return The tunnelConnAttemptCount.
       */
      int getTunnelConnAttemptCount();

      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       * @return Whether the lastTimeTunnelWentDown field is set.
       */
      boolean hasLastTimeTunnelWentDown();
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       * @return The lastTimeTunnelWentDown.
       */
      com.google.protobuf.Timestamp getLastTimeTunnelWentDown();
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       */
      com.google.protobuf.TimestampOrBuilder getLastTimeTunnelWentDownOrBuilder();

      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       * @return Whether the lastTimeTunnelEstablished field is set.
       */
      boolean hasLastTimeTunnelEstablished();
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       * @return The lastTimeTunnelEstablished.
       */
      com.google.protobuf.Timestamp getLastTimeTunnelEstablished();
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       */
      com.google.protobuf.TimestampOrBuilder getLastTimeTunnelEstablishedOrBuilder();

      /**
       * <code>uint32 droppedMessagesCount = 9;</code>
       * @return The droppedMessagesCount.
       */
      int getDroppedMessagesCount();

      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
       * @return The enum numeric value on the wire for currentTunnelState.
       */
      int getCurrentTunnelStateValue();
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
       * @return The currentTunnelState.
       */
      weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState getCurrentTunnelState();

      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
       * @return The enum numeric value on the wire for currentActiveTunnel.
       */
      int getCurrentActiveTunnelValue();
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
       * @return The currentActiveTunnel.
       */
      weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType getCurrentActiveTunnel();
    }
    /**
     * Protobuf type {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent}
     */
    public static final class TelemetryTunnelStatsEvent extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)
        TelemetryTunnelStatsEventOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use TelemetryTunnelStatsEvent.newBuilder() to construct.
      private TelemetryTunnelStatsEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private TelemetryTunnelStatsEvent() {
        txBytesToService_ = "";
        rxBytesFromService_ = "";
        currentTunnelState_ = 0;
        currentActiveTunnel_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new TelemetryTunnelStatsEvent();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private TelemetryTunnelStatsEvent(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                txBytesToService_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                rxBytesFromService_ = s;
                break;
              }
              case 24: {

                txMessagesToService_ = input.readUInt32();
                break;
              }
              case 32: {

                rxMessagesFromService_ = input.readUInt32();
                break;
              }
              case 40: {

                tunnelDownCount_ = input.readUInt32();
                break;
              }
              case 48: {

                tunnelConnAttemptCount_ = input.readUInt32();
                break;
              }
              case 58: {
                com.google.protobuf.Timestamp.Builder subBuilder = null;
                if (lastTimeTunnelWentDown_ != null) {
                  subBuilder = lastTimeTunnelWentDown_.toBuilder();
                }
                lastTimeTunnelWentDown_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(lastTimeTunnelWentDown_);
                  lastTimeTunnelWentDown_ = subBuilder.buildPartial();
                }

                break;
              }
              case 66: {
                com.google.protobuf.Timestamp.Builder subBuilder = null;
                if (lastTimeTunnelEstablished_ != null) {
                  subBuilder = lastTimeTunnelEstablished_.toBuilder();
                }
                lastTimeTunnelEstablished_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(lastTimeTunnelEstablished_);
                  lastTimeTunnelEstablished_ = subBuilder.buildPartial();
                }

                break;
              }
              case 72: {

                droppedMessagesCount_ = input.readUInt32();
                break;
              }
              case 80: {
                int rawValue = input.readEnum();

                currentTunnelState_ = rawValue;
                break;
              }
              case 88: {
                int rawValue = input.readEnum();

                currentActiveTunnel_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.class, weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.Builder.class);
      }

      public static final int TXBYTESTOSERVICE_FIELD_NUMBER = 1;
      private volatile java.lang.Object txBytesToService_;
      /**
       * <code>string txBytesToService = 1;</code>
       * @return The txBytesToService.
       */
      @java.lang.Override
      public java.lang.String getTxBytesToService() {
        java.lang.Object ref = txBytesToService_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txBytesToService_ = s;
          return s;
        }
      }
      /**
       * <code>string txBytesToService = 1;</code>
       * @return The bytes for txBytesToService.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTxBytesToServiceBytes() {
        java.lang.Object ref = txBytesToService_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txBytesToService_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RXBYTESFROMSERVICE_FIELD_NUMBER = 2;
      private volatile java.lang.Object rxBytesFromService_;
      /**
       * <code>string rxBytesFromService = 2;</code>
       * @return The rxBytesFromService.
       */
      @java.lang.Override
      public java.lang.String getRxBytesFromService() {
        java.lang.Object ref = rxBytesFromService_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rxBytesFromService_ = s;
          return s;
        }
      }
      /**
       * <code>string rxBytesFromService = 2;</code>
       * @return The bytes for rxBytesFromService.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRxBytesFromServiceBytes() {
        java.lang.Object ref = rxBytesFromService_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rxBytesFromService_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TXMESSAGESTOSERVICE_FIELD_NUMBER = 3;
      private int txMessagesToService_;
      /**
       * <code>uint32 txMessagesToService = 3;</code>
       * @return The txMessagesToService.
       */
      @java.lang.Override
      public int getTxMessagesToService() {
        return txMessagesToService_;
      }

      public static final int RXMESSAGESFROMSERVICE_FIELD_NUMBER = 4;
      private int rxMessagesFromService_;
      /**
       * <code>uint32 rxMessagesFromService = 4;</code>
       * @return The rxMessagesFromService.
       */
      @java.lang.Override
      public int getRxMessagesFromService() {
        return rxMessagesFromService_;
      }

      public static final int TUNNELDOWNCOUNT_FIELD_NUMBER = 5;
      private int tunnelDownCount_;
      /**
       * <code>uint32 tunnelDownCount = 5;</code>
       * @return The tunnelDownCount.
       */
      @java.lang.Override
      public int getTunnelDownCount() {
        return tunnelDownCount_;
      }

      public static final int TUNNELCONNATTEMPTCOUNT_FIELD_NUMBER = 6;
      private int tunnelConnAttemptCount_;
      /**
       * <code>uint32 tunnelConnAttemptCount = 6;</code>
       * @return The tunnelConnAttemptCount.
       */
      @java.lang.Override
      public int getTunnelConnAttemptCount() {
        return tunnelConnAttemptCount_;
      }

      public static final int LASTTIMETUNNELWENTDOWN_FIELD_NUMBER = 7;
      private com.google.protobuf.Timestamp lastTimeTunnelWentDown_;
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       * @return Whether the lastTimeTunnelWentDown field is set.
       */
      @java.lang.Override
      public boolean hasLastTimeTunnelWentDown() {
        return lastTimeTunnelWentDown_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       * @return The lastTimeTunnelWentDown.
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getLastTimeTunnelWentDown() {
        return lastTimeTunnelWentDown_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelWentDown_;
      }
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
       */
      @java.lang.Override
      public com.google.protobuf.TimestampOrBuilder getLastTimeTunnelWentDownOrBuilder() {
        return getLastTimeTunnelWentDown();
      }

      public static final int LASTTIMETUNNELESTABLISHED_FIELD_NUMBER = 8;
      private com.google.protobuf.Timestamp lastTimeTunnelEstablished_;
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       * @return Whether the lastTimeTunnelEstablished field is set.
       */
      @java.lang.Override
      public boolean hasLastTimeTunnelEstablished() {
        return lastTimeTunnelEstablished_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       * @return The lastTimeTunnelEstablished.
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getLastTimeTunnelEstablished() {
        return lastTimeTunnelEstablished_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelEstablished_;
      }
      /**
       * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
       */
      @java.lang.Override
      public com.google.protobuf.TimestampOrBuilder getLastTimeTunnelEstablishedOrBuilder() {
        return getLastTimeTunnelEstablished();
      }

      public static final int DROPPEDMESSAGESCOUNT_FIELD_NUMBER = 9;
      private int droppedMessagesCount_;
      /**
       * <code>uint32 droppedMessagesCount = 9;</code>
       * @return The droppedMessagesCount.
       */
      @java.lang.Override
      public int getDroppedMessagesCount() {
        return droppedMessagesCount_;
      }

      public static final int CURRENTTUNNELSTATE_FIELD_NUMBER = 10;
      private int currentTunnelState_;
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
       * @return The enum numeric value on the wire for currentTunnelState.
       */
      @java.lang.Override public int getCurrentTunnelStateValue() {
        return currentTunnelState_;
      }
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
       * @return The currentTunnelState.
       */
      @java.lang.Override public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState getCurrentTunnelState() {
        @SuppressWarnings("deprecation")
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState result = weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.valueOf(currentTunnelState_);
        return result == null ? weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.UNRECOGNIZED : result;
      }

      public static final int CURRENTACTIVETUNNEL_FIELD_NUMBER = 11;
      private int currentActiveTunnel_;
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
       * @return The enum numeric value on the wire for currentActiveTunnel.
       */
      @java.lang.Override public int getCurrentActiveTunnelValue() {
        return currentActiveTunnel_;
      }
      /**
       * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
       * @return The currentActiveTunnel.
       */
      @java.lang.Override public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType getCurrentActiveTunnel() {
        @SuppressWarnings("deprecation")
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType result = weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.valueOf(currentActiveTunnel_);
        return result == null ? weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getTxBytesToServiceBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txBytesToService_);
        }
        if (!getRxBytesFromServiceBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rxBytesFromService_);
        }
        if (txMessagesToService_ != 0) {
          output.writeUInt32(3, txMessagesToService_);
        }
        if (rxMessagesFromService_ != 0) {
          output.writeUInt32(4, rxMessagesFromService_);
        }
        if (tunnelDownCount_ != 0) {
          output.writeUInt32(5, tunnelDownCount_);
        }
        if (tunnelConnAttemptCount_ != 0) {
          output.writeUInt32(6, tunnelConnAttemptCount_);
        }
        if (lastTimeTunnelWentDown_ != null) {
          output.writeMessage(7, getLastTimeTunnelWentDown());
        }
        if (lastTimeTunnelEstablished_ != null) {
          output.writeMessage(8, getLastTimeTunnelEstablished());
        }
        if (droppedMessagesCount_ != 0) {
          output.writeUInt32(9, droppedMessagesCount_);
        }
        if (currentTunnelState_ != weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.TUNNEL_STATE_UNSPECIFIED.getNumber()) {
          output.writeEnum(10, currentTunnelState_);
        }
        if (currentActiveTunnel_ != weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.TUNNEL_TYPE_UNSPECIFIED.getNumber()) {
          output.writeEnum(11, currentActiveTunnel_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTxBytesToServiceBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txBytesToService_);
        }
        if (!getRxBytesFromServiceBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rxBytesFromService_);
        }
        if (txMessagesToService_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, txMessagesToService_);
        }
        if (rxMessagesFromService_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, rxMessagesFromService_);
        }
        if (tunnelDownCount_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, tunnelDownCount_);
        }
        if (tunnelConnAttemptCount_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(6, tunnelConnAttemptCount_);
        }
        if (lastTimeTunnelWentDown_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, getLastTimeTunnelWentDown());
        }
        if (lastTimeTunnelEstablished_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, getLastTimeTunnelEstablished());
        }
        if (droppedMessagesCount_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(9, droppedMessagesCount_);
        }
        if (currentTunnelState_ != weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.TUNNEL_STATE_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(10, currentTunnelState_);
        }
        if (currentActiveTunnel_ != weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.TUNNEL_TYPE_UNSPECIFIED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(11, currentActiveTunnel_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)) {
          return super.equals(obj);
        }
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent other = (weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent) obj;

        if (!getTxBytesToService()
            .equals(other.getTxBytesToService())) return false;
        if (!getRxBytesFromService()
            .equals(other.getRxBytesFromService())) return false;
        if (getTxMessagesToService()
            != other.getTxMessagesToService()) return false;
        if (getRxMessagesFromService()
            != other.getRxMessagesFromService()) return false;
        if (getTunnelDownCount()
            != other.getTunnelDownCount()) return false;
        if (getTunnelConnAttemptCount()
            != other.getTunnelConnAttemptCount()) return false;
        if (hasLastTimeTunnelWentDown() != other.hasLastTimeTunnelWentDown()) return false;
        if (hasLastTimeTunnelWentDown()) {
          if (!getLastTimeTunnelWentDown()
              .equals(other.getLastTimeTunnelWentDown())) return false;
        }
        if (hasLastTimeTunnelEstablished() != other.hasLastTimeTunnelEstablished()) return false;
        if (hasLastTimeTunnelEstablished()) {
          if (!getLastTimeTunnelEstablished()
              .equals(other.getLastTimeTunnelEstablished())) return false;
        }
        if (getDroppedMessagesCount()
            != other.getDroppedMessagesCount()) return false;
        if (currentTunnelState_ != other.currentTunnelState_) return false;
        if (currentActiveTunnel_ != other.currentActiveTunnel_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TXBYTESTOSERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getTxBytesToService().hashCode();
        hash = (37 * hash) + RXBYTESFROMSERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getRxBytesFromService().hashCode();
        hash = (37 * hash) + TXMESSAGESTOSERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getTxMessagesToService();
        hash = (37 * hash) + RXMESSAGESFROMSERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getRxMessagesFromService();
        hash = (37 * hash) + TUNNELDOWNCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getTunnelDownCount();
        hash = (37 * hash) + TUNNELCONNATTEMPTCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getTunnelConnAttemptCount();
        if (hasLastTimeTunnelWentDown()) {
          hash = (37 * hash) + LASTTIMETUNNELWENTDOWN_FIELD_NUMBER;
          hash = (53 * hash) + getLastTimeTunnelWentDown().hashCode();
        }
        if (hasLastTimeTunnelEstablished()) {
          hash = (37 * hash) + LASTTIMETUNNELESTABLISHED_FIELD_NUMBER;
          hash = (53 * hash) + getLastTimeTunnelEstablished().hashCode();
        }
        hash = (37 * hash) + DROPPEDMESSAGESCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getDroppedMessagesCount();
        hash = (37 * hash) + CURRENTTUNNELSTATE_FIELD_NUMBER;
        hash = (53 * hash) + currentTunnelState_;
        hash = (37 * hash) + CURRENTACTIVETUNNEL_FIELD_NUMBER;
        hash = (53 * hash) + currentActiveTunnel_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEventOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.class, weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.Builder.class);
        }

        // Construct using weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          txBytesToService_ = "";

          rxBytesFromService_ = "";

          txMessagesToService_ = 0;

          rxMessagesFromService_ = 0;

          tunnelDownCount_ = 0;

          tunnelConnAttemptCount_ = 0;

          if (lastTimeTunnelWentDownBuilder_ == null) {
            lastTimeTunnelWentDown_ = null;
          } else {
            lastTimeTunnelWentDown_ = null;
            lastTimeTunnelWentDownBuilder_ = null;
          }
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            lastTimeTunnelEstablished_ = null;
          } else {
            lastTimeTunnelEstablished_ = null;
            lastTimeTunnelEstablishedBuilder_ = null;
          }
          droppedMessagesCount_ = 0;

          currentTunnelState_ = 0;

          currentActiveTunnel_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor;
        }

        @java.lang.Override
        public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent getDefaultInstanceForType() {
          return weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.getDefaultInstance();
        }

        @java.lang.Override
        public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent build() {
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent buildPartial() {
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent result = new weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent(this);
          result.txBytesToService_ = txBytesToService_;
          result.rxBytesFromService_ = rxBytesFromService_;
          result.txMessagesToService_ = txMessagesToService_;
          result.rxMessagesFromService_ = rxMessagesFromService_;
          result.tunnelDownCount_ = tunnelDownCount_;
          result.tunnelConnAttemptCount_ = tunnelConnAttemptCount_;
          if (lastTimeTunnelWentDownBuilder_ == null) {
            result.lastTimeTunnelWentDown_ = lastTimeTunnelWentDown_;
          } else {
            result.lastTimeTunnelWentDown_ = lastTimeTunnelWentDownBuilder_.build();
          }
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            result.lastTimeTunnelEstablished_ = lastTimeTunnelEstablished_;
          } else {
            result.lastTimeTunnelEstablished_ = lastTimeTunnelEstablishedBuilder_.build();
          }
          result.droppedMessagesCount_ = droppedMessagesCount_;
          result.currentTunnelState_ = currentTunnelState_;
          result.currentActiveTunnel_ = currentActiveTunnel_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent) {
            return mergeFrom((weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent other) {
          if (other == weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent.getDefaultInstance()) return this;
          if (!other.getTxBytesToService().isEmpty()) {
            txBytesToService_ = other.txBytesToService_;
            onChanged();
          }
          if (!other.getRxBytesFromService().isEmpty()) {
            rxBytesFromService_ = other.rxBytesFromService_;
            onChanged();
          }
          if (other.getTxMessagesToService() != 0) {
            setTxMessagesToService(other.getTxMessagesToService());
          }
          if (other.getRxMessagesFromService() != 0) {
            setRxMessagesFromService(other.getRxMessagesFromService());
          }
          if (other.getTunnelDownCount() != 0) {
            setTunnelDownCount(other.getTunnelDownCount());
          }
          if (other.getTunnelConnAttemptCount() != 0) {
            setTunnelConnAttemptCount(other.getTunnelConnAttemptCount());
          }
          if (other.hasLastTimeTunnelWentDown()) {
            mergeLastTimeTunnelWentDown(other.getLastTimeTunnelWentDown());
          }
          if (other.hasLastTimeTunnelEstablished()) {
            mergeLastTimeTunnelEstablished(other.getLastTimeTunnelEstablished());
          }
          if (other.getDroppedMessagesCount() != 0) {
            setDroppedMessagesCount(other.getDroppedMessagesCount());
          }
          if (other.currentTunnelState_ != 0) {
            setCurrentTunnelStateValue(other.getCurrentTunnelStateValue());
          }
          if (other.currentActiveTunnel_ != 0) {
            setCurrentActiveTunnelValue(other.getCurrentActiveTunnelValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object txBytesToService_ = "";
        /**
         * <code>string txBytesToService = 1;</code>
         * @return The txBytesToService.
         */
        public java.lang.String getTxBytesToService() {
          java.lang.Object ref = txBytesToService_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            txBytesToService_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string txBytesToService = 1;</code>
         * @return The bytes for txBytesToService.
         */
        public com.google.protobuf.ByteString
            getTxBytesToServiceBytes() {
          java.lang.Object ref = txBytesToService_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            txBytesToService_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string txBytesToService = 1;</code>
         * @param value The txBytesToService to set.
         * @return This builder for chaining.
         */
        public Builder setTxBytesToService(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          txBytesToService_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string txBytesToService = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTxBytesToService() {
          
          txBytesToService_ = getDefaultInstance().getTxBytesToService();
          onChanged();
          return this;
        }
        /**
         * <code>string txBytesToService = 1;</code>
         * @param value The bytes for txBytesToService to set.
         * @return This builder for chaining.
         */
        public Builder setTxBytesToServiceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          txBytesToService_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object rxBytesFromService_ = "";
        /**
         * <code>string rxBytesFromService = 2;</code>
         * @return The rxBytesFromService.
         */
        public java.lang.String getRxBytesFromService() {
          java.lang.Object ref = rxBytesFromService_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rxBytesFromService_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string rxBytesFromService = 2;</code>
         * @return The bytes for rxBytesFromService.
         */
        public com.google.protobuf.ByteString
            getRxBytesFromServiceBytes() {
          java.lang.Object ref = rxBytesFromService_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            rxBytesFromService_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string rxBytesFromService = 2;</code>
         * @param value The rxBytesFromService to set.
         * @return This builder for chaining.
         */
        public Builder setRxBytesFromService(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rxBytesFromService_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string rxBytesFromService = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearRxBytesFromService() {
          
          rxBytesFromService_ = getDefaultInstance().getRxBytesFromService();
          onChanged();
          return this;
        }
        /**
         * <code>string rxBytesFromService = 2;</code>
         * @param value The bytes for rxBytesFromService to set.
         * @return This builder for chaining.
         */
        public Builder setRxBytesFromServiceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          rxBytesFromService_ = value;
          onChanged();
          return this;
        }

        private int txMessagesToService_ ;
        /**
         * <code>uint32 txMessagesToService = 3;</code>
         * @return The txMessagesToService.
         */
        @java.lang.Override
        public int getTxMessagesToService() {
          return txMessagesToService_;
        }
        /**
         * <code>uint32 txMessagesToService = 3;</code>
         * @param value The txMessagesToService to set.
         * @return This builder for chaining.
         */
        public Builder setTxMessagesToService(int value) {
          
          txMessagesToService_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 txMessagesToService = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearTxMessagesToService() {
          
          txMessagesToService_ = 0;
          onChanged();
          return this;
        }

        private int rxMessagesFromService_ ;
        /**
         * <code>uint32 rxMessagesFromService = 4;</code>
         * @return The rxMessagesFromService.
         */
        @java.lang.Override
        public int getRxMessagesFromService() {
          return rxMessagesFromService_;
        }
        /**
         * <code>uint32 rxMessagesFromService = 4;</code>
         * @param value The rxMessagesFromService to set.
         * @return This builder for chaining.
         */
        public Builder setRxMessagesFromService(int value) {
          
          rxMessagesFromService_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 rxMessagesFromService = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearRxMessagesFromService() {
          
          rxMessagesFromService_ = 0;
          onChanged();
          return this;
        }

        private int tunnelDownCount_ ;
        /**
         * <code>uint32 tunnelDownCount = 5;</code>
         * @return The tunnelDownCount.
         */
        @java.lang.Override
        public int getTunnelDownCount() {
          return tunnelDownCount_;
        }
        /**
         * <code>uint32 tunnelDownCount = 5;</code>
         * @param value The tunnelDownCount to set.
         * @return This builder for chaining.
         */
        public Builder setTunnelDownCount(int value) {
          
          tunnelDownCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 tunnelDownCount = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearTunnelDownCount() {
          
          tunnelDownCount_ = 0;
          onChanged();
          return this;
        }

        private int tunnelConnAttemptCount_ ;
        /**
         * <code>uint32 tunnelConnAttemptCount = 6;</code>
         * @return The tunnelConnAttemptCount.
         */
        @java.lang.Override
        public int getTunnelConnAttemptCount() {
          return tunnelConnAttemptCount_;
        }
        /**
         * <code>uint32 tunnelConnAttemptCount = 6;</code>
         * @param value The tunnelConnAttemptCount to set.
         * @return This builder for chaining.
         */
        public Builder setTunnelConnAttemptCount(int value) {
          
          tunnelConnAttemptCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 tunnelConnAttemptCount = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearTunnelConnAttemptCount() {
          
          tunnelConnAttemptCount_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.Timestamp lastTimeTunnelWentDown_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastTimeTunnelWentDownBuilder_;
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         * @return Whether the lastTimeTunnelWentDown field is set.
         */
        public boolean hasLastTimeTunnelWentDown() {
          return lastTimeTunnelWentDownBuilder_ != null || lastTimeTunnelWentDown_ != null;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         * @return The lastTimeTunnelWentDown.
         */
        public com.google.protobuf.Timestamp getLastTimeTunnelWentDown() {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            return lastTimeTunnelWentDown_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelWentDown_;
          } else {
            return lastTimeTunnelWentDownBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public Builder setLastTimeTunnelWentDown(com.google.protobuf.Timestamp value) {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            lastTimeTunnelWentDown_ = value;
            onChanged();
          } else {
            lastTimeTunnelWentDownBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public Builder setLastTimeTunnelWentDown(
            com.google.protobuf.Timestamp.Builder builderForValue) {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            lastTimeTunnelWentDown_ = builderForValue.build();
            onChanged();
          } else {
            lastTimeTunnelWentDownBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public Builder mergeLastTimeTunnelWentDown(com.google.protobuf.Timestamp value) {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            if (lastTimeTunnelWentDown_ != null) {
              lastTimeTunnelWentDown_ =
                com.google.protobuf.Timestamp.newBuilder(lastTimeTunnelWentDown_).mergeFrom(value).buildPartial();
            } else {
              lastTimeTunnelWentDown_ = value;
            }
            onChanged();
          } else {
            lastTimeTunnelWentDownBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public Builder clearLastTimeTunnelWentDown() {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            lastTimeTunnelWentDown_ = null;
            onChanged();
          } else {
            lastTimeTunnelWentDown_ = null;
            lastTimeTunnelWentDownBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public com.google.protobuf.Timestamp.Builder getLastTimeTunnelWentDownBuilder() {
          
          onChanged();
          return getLastTimeTunnelWentDownFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getLastTimeTunnelWentDownOrBuilder() {
          if (lastTimeTunnelWentDownBuilder_ != null) {
            return lastTimeTunnelWentDownBuilder_.getMessageOrBuilder();
          } else {
            return lastTimeTunnelWentDown_ == null ?
                com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelWentDown_;
          }
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelWentDown = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
            getLastTimeTunnelWentDownFieldBuilder() {
          if (lastTimeTunnelWentDownBuilder_ == null) {
            lastTimeTunnelWentDownBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                    getLastTimeTunnelWentDown(),
                    getParentForChildren(),
                    isClean());
            lastTimeTunnelWentDown_ = null;
          }
          return lastTimeTunnelWentDownBuilder_;
        }

        private com.google.protobuf.Timestamp lastTimeTunnelEstablished_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastTimeTunnelEstablishedBuilder_;
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         * @return Whether the lastTimeTunnelEstablished field is set.
         */
        public boolean hasLastTimeTunnelEstablished() {
          return lastTimeTunnelEstablishedBuilder_ != null || lastTimeTunnelEstablished_ != null;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         * @return The lastTimeTunnelEstablished.
         */
        public com.google.protobuf.Timestamp getLastTimeTunnelEstablished() {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            return lastTimeTunnelEstablished_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelEstablished_;
          } else {
            return lastTimeTunnelEstablishedBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public Builder setLastTimeTunnelEstablished(com.google.protobuf.Timestamp value) {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            lastTimeTunnelEstablished_ = value;
            onChanged();
          } else {
            lastTimeTunnelEstablishedBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public Builder setLastTimeTunnelEstablished(
            com.google.protobuf.Timestamp.Builder builderForValue) {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            lastTimeTunnelEstablished_ = builderForValue.build();
            onChanged();
          } else {
            lastTimeTunnelEstablishedBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public Builder mergeLastTimeTunnelEstablished(com.google.protobuf.Timestamp value) {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            if (lastTimeTunnelEstablished_ != null) {
              lastTimeTunnelEstablished_ =
                com.google.protobuf.Timestamp.newBuilder(lastTimeTunnelEstablished_).mergeFrom(value).buildPartial();
            } else {
              lastTimeTunnelEstablished_ = value;
            }
            onChanged();
          } else {
            lastTimeTunnelEstablishedBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public Builder clearLastTimeTunnelEstablished() {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            lastTimeTunnelEstablished_ = null;
            onChanged();
          } else {
            lastTimeTunnelEstablished_ = null;
            lastTimeTunnelEstablishedBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public com.google.protobuf.Timestamp.Builder getLastTimeTunnelEstablishedBuilder() {
          
          onChanged();
          return getLastTimeTunnelEstablishedFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getLastTimeTunnelEstablishedOrBuilder() {
          if (lastTimeTunnelEstablishedBuilder_ != null) {
            return lastTimeTunnelEstablishedBuilder_.getMessageOrBuilder();
          } else {
            return lastTimeTunnelEstablished_ == null ?
                com.google.protobuf.Timestamp.getDefaultInstance() : lastTimeTunnelEstablished_;
          }
        }
        /**
         * <code>.google.protobuf.Timestamp lastTimeTunnelEstablished = 8;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
            getLastTimeTunnelEstablishedFieldBuilder() {
          if (lastTimeTunnelEstablishedBuilder_ == null) {
            lastTimeTunnelEstablishedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                    getLastTimeTunnelEstablished(),
                    getParentForChildren(),
                    isClean());
            lastTimeTunnelEstablished_ = null;
          }
          return lastTimeTunnelEstablishedBuilder_;
        }

        private int droppedMessagesCount_ ;
        /**
         * <code>uint32 droppedMessagesCount = 9;</code>
         * @return The droppedMessagesCount.
         */
        @java.lang.Override
        public int getDroppedMessagesCount() {
          return droppedMessagesCount_;
        }
        /**
         * <code>uint32 droppedMessagesCount = 9;</code>
         * @param value The droppedMessagesCount to set.
         * @return This builder for chaining.
         */
        public Builder setDroppedMessagesCount(int value) {
          
          droppedMessagesCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 droppedMessagesCount = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearDroppedMessagesCount() {
          
          droppedMessagesCount_ = 0;
          onChanged();
          return this;
        }

        private int currentTunnelState_ = 0;
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
         * @return The enum numeric value on the wire for currentTunnelState.
         */
        @java.lang.Override public int getCurrentTunnelStateValue() {
          return currentTunnelState_;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
         * @param value The enum numeric value on the wire for currentTunnelState to set.
         * @return This builder for chaining.
         */
        public Builder setCurrentTunnelStateValue(int value) {
          
          currentTunnelState_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
         * @return The currentTunnelState.
         */
        @java.lang.Override
        public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState getCurrentTunnelState() {
          @SuppressWarnings("deprecation")
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState result = weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.valueOf(currentTunnelState_);
          return result == null ? weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState.UNRECOGNIZED : result;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
         * @param value The currentTunnelState to set.
         * @return This builder for chaining.
         */
        public Builder setCurrentTunnelState(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelState value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          currentTunnelState_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelState currentTunnelState = 10;</code>
         * @return This builder for chaining.
         */
        public Builder clearCurrentTunnelState() {
          
          currentTunnelState_ = 0;
          onChanged();
          return this;
        }

        private int currentActiveTunnel_ = 0;
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
         * @return The enum numeric value on the wire for currentActiveTunnel.
         */
        @java.lang.Override public int getCurrentActiveTunnelValue() {
          return currentActiveTunnel_;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
         * @param value The enum numeric value on the wire for currentActiveTunnel to set.
         * @return This builder for chaining.
         */
        public Builder setCurrentActiveTunnelValue(int value) {
          
          currentActiveTunnel_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
         * @return The currentActiveTunnel.
         */
        @java.lang.Override
        public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType getCurrentActiveTunnel() {
          @SuppressWarnings("deprecation")
          weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType result = weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.valueOf(currentActiveTunnel_);
          return result == null ? weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType.UNRECOGNIZED : result;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
         * @param value The currentActiveTunnel to set.
         * @return This builder for chaining.
         */
        public Builder setCurrentActiveTunnel(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TunnelType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          currentActiveTunnel_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TunnelType currentActiveTunnel = 11;</code>
         * @return This builder for chaining.
         */
        public Builder clearCurrentActiveTunnel() {
          
          currentActiveTunnel_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)
      }

      // @@protoc_insertion_point(class_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent)
      private static final weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent();
      }

      public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<TelemetryTunnelStatsEvent>
          PARSER = new com.google.protobuf.AbstractParser<TelemetryTunnelStatsEvent>() {
        @java.lang.Override
        public TelemetryTunnelStatsEvent parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TelemetryTunnelStatsEvent(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<TelemetryTunnelStatsEvent> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<TelemetryTunnelStatsEvent> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.TelemetryTunnelStatsEvent getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait)) {
        return super.equals(obj);
      }
      weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait other = (weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.telemetry.tunnel.TelemetryTunnelTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.telemetry.tunnel.TelemetryTunnelTrait)
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.class, weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.Builder.class);
      }

      // Construct using weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.telemetry.tunnel.Tunnel.internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait getDefaultInstanceForType() {
        return weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait build() {
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait buildPartial() {
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait result = new weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait) {
          return mergeFrom((weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait other) {
        if (other == weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.telemetry.tunnel.TelemetryTunnelTrait)
    private static final weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait();
    }

    public static weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TelemetryTunnelTrait>
        PARSER = new com.google.protobuf.AbstractParser<TelemetryTunnelTrait>() {
      @java.lang.Override
      public TelemetryTunnelTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TelemetryTunnelTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TelemetryTunnelTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TelemetryTunnelTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.telemetry.tunnel.Tunnel.TelemetryTunnelTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"weave/trait/telemetry/tunnel.proto\022\034we" +
      "ave.trait.telemetry.tunnel\032\037google/proto" +
      "buf/timestamp.proto\"\210\007\n\024TelemetryTunnelT" +
      "rait\032\227\004\n\031TelemetryTunnelStatsEvent\022\030\n\020tx" +
      "BytesToService\030\001 \001(\t\022\032\n\022rxBytesFromServi" +
      "ce\030\002 \001(\t\022\033\n\023txMessagesToService\030\003 \001(\r\022\035\n" +
      "\025rxMessagesFromService\030\004 \001(\r\022\027\n\017tunnelDo" +
      "wnCount\030\005 \001(\r\022\036\n\026tunnelConnAttemptCount\030" +
      "\006 \001(\r\022:\n\026lastTimeTunnelWentDown\030\007 \001(\0132\032." +
      "google.protobuf.Timestamp\022=\n\031lastTimeTun" +
      "nelEstablished\030\010 \001(\0132\032.google.protobuf.T" +
      "imestamp\022\034\n\024droppedMessagesCount\030\t \001(\r\022Z" +
      "\n\022currentTunnelState\030\n \001(\0162>.weave.trait" +
      ".telemetry.tunnel.TelemetryTunnelTrait.T" +
      "unnelState\022Z\n\023currentActiveTunnel\030\013 \001(\0162" +
      "=.weave.trait.telemetry.tunnel.Telemetry" +
      "TunnelTrait.TunnelType\"\212\001\n\nTunnelType\022\033\n" +
      "\027TUNNEL_TYPE_UNSPECIFIED\020\000\022\024\n\020TUNNEL_TYP" +
      "E_NONE\020\001\022\027\n\023TUNNEL_TYPE_PRIMARY\020\002\022\026\n\022TUN" +
      "NEL_TYPE_BACKUP\020\003\022\030\n\024TUNNEL_TYPE_SHORTCU" +
      "T\020\004\"\310\001\n\013TunnelState\022\034\n\030TUNNEL_STATE_UNSP" +
      "ECIFIED\020\000\022\032\n\026TUNNEL_STATE_NO_TUNNEL\020\001\022$\n" +
      " TUNNEL_STATE_PRIMARY_ESTABLISHED\020\002\022(\n$T" +
      "UNNEL_STATE_BACKUP_ONLY_ESTABLISHED\020\003\022/\n" +
      "+TUNNEL_STATE_PRIMARY_AND_BACKUP_ESTABLI" +
      "SHED\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor,
        new java.lang.String[] { });
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor =
      internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_descriptor.getNestedTypes().get(0);
    internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_telemetry_tunnel_TelemetryTunnelTrait_TelemetryTunnelStatsEvent_descriptor,
        new java.lang.String[] { "TxBytesToService", "RxBytesFromService", "TxMessagesToService", "RxMessagesFromService", "TunnelDownCount", "TunnelConnAttemptCount", "LastTimeTunnelWentDown", "LastTimeTunnelEstablished", "DroppedMessagesCount", "CurrentTunnelState", "CurrentActiveTunnel", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
