// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weave/trait/audio.proto

package weave.trait.audio;

public final class Audio {
  private Audio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BasicVolumeCapabilitiesTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.audio.BasicVolumeCapabilitiesTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 volumeSetPointCount = 1;</code>
     * @return The volumeSetPointCount.
     */
    int getVolumeSetPointCount();
  }
  /**
   * Protobuf type {@code weave.trait.audio.BasicVolumeCapabilitiesTrait}
   */
  public static final class BasicVolumeCapabilitiesTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.audio.BasicVolumeCapabilitiesTrait)
      BasicVolumeCapabilitiesTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BasicVolumeCapabilitiesTrait.newBuilder() to construct.
    private BasicVolumeCapabilitiesTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BasicVolumeCapabilitiesTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BasicVolumeCapabilitiesTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BasicVolumeCapabilitiesTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              volumeSetPointCount_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.class, weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.Builder.class);
    }

    public static final int VOLUMESETPOINTCOUNT_FIELD_NUMBER = 1;
    private int volumeSetPointCount_;
    /**
     * <code>uint32 volumeSetPointCount = 1;</code>
     * @return The volumeSetPointCount.
     */
    @java.lang.Override
    public int getVolumeSetPointCount() {
      return volumeSetPointCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (volumeSetPointCount_ != 0) {
        output.writeUInt32(1, volumeSetPointCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (volumeSetPointCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, volumeSetPointCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait)) {
        return super.equals(obj);
      }
      weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait other = (weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait) obj;

      if (getVolumeSetPointCount()
          != other.getVolumeSetPointCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOLUMESETPOINTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getVolumeSetPointCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.audio.BasicVolumeCapabilitiesTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.audio.BasicVolumeCapabilitiesTrait)
        weave.trait.audio.Audio.BasicVolumeCapabilitiesTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.class, weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.Builder.class);
      }

      // Construct using weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        volumeSetPointCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait getDefaultInstanceForType() {
        return weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait build() {
        weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait buildPartial() {
        weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait result = new weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait(this);
        result.volumeSetPointCount_ = volumeSetPointCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait) {
          return mergeFrom((weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait other) {
        if (other == weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait.getDefaultInstance()) return this;
        if (other.getVolumeSetPointCount() != 0) {
          setVolumeSetPointCount(other.getVolumeSetPointCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int volumeSetPointCount_ ;
      /**
       * <code>uint32 volumeSetPointCount = 1;</code>
       * @return The volumeSetPointCount.
       */
      @java.lang.Override
      public int getVolumeSetPointCount() {
        return volumeSetPointCount_;
      }
      /**
       * <code>uint32 volumeSetPointCount = 1;</code>
       * @param value The volumeSetPointCount to set.
       * @return This builder for chaining.
       */
      public Builder setVolumeSetPointCount(int value) {
        
        volumeSetPointCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 volumeSetPointCount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumeSetPointCount() {
        
        volumeSetPointCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.audio.BasicVolumeCapabilitiesTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.audio.BasicVolumeCapabilitiesTrait)
    private static final weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait();
    }

    public static weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BasicVolumeCapabilitiesTrait>
        PARSER = new com.google.protobuf.AbstractParser<BasicVolumeCapabilitiesTrait>() {
      @java.lang.Override
      public BasicVolumeCapabilitiesTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BasicVolumeCapabilitiesTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BasicVolumeCapabilitiesTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BasicVolumeCapabilitiesTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.audio.Audio.BasicVolumeCapabilitiesTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BasicVolumeTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.audio.BasicVolumeTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 volume = 1;</code>
     * @return The volume.
     */
    int getVolume();

    /**
     * <code>bool mute = 2;</code>
     * @return The mute.
     */
    boolean getMute();
  }
  /**
   * Protobuf type {@code weave.trait.audio.BasicVolumeTrait}
   */
  public static final class BasicVolumeTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.audio.BasicVolumeTrait)
      BasicVolumeTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BasicVolumeTrait.newBuilder() to construct.
    private BasicVolumeTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BasicVolumeTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BasicVolumeTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BasicVolumeTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              volume_ = input.readUInt32();
              break;
            }
            case 16: {

              mute_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.audio.Audio.BasicVolumeTrait.class, weave.trait.audio.Audio.BasicVolumeTrait.Builder.class);
    }

    public static final int VOLUME_FIELD_NUMBER = 1;
    private int volume_;
    /**
     * <code>uint32 volume = 1;</code>
     * @return The volume.
     */
    @java.lang.Override
    public int getVolume() {
      return volume_;
    }

    public static final int MUTE_FIELD_NUMBER = 2;
    private boolean mute_;
    /**
     * <code>bool mute = 2;</code>
     * @return The mute.
     */
    @java.lang.Override
    public boolean getMute() {
      return mute_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (volume_ != 0) {
        output.writeUInt32(1, volume_);
      }
      if (mute_ != false) {
        output.writeBool(2, mute_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (volume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, volume_);
      }
      if (mute_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, mute_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.audio.Audio.BasicVolumeTrait)) {
        return super.equals(obj);
      }
      weave.trait.audio.Audio.BasicVolumeTrait other = (weave.trait.audio.Audio.BasicVolumeTrait) obj;

      if (getVolume()
          != other.getVolume()) return false;
      if (getMute()
          != other.getMute()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getVolume();
      hash = (37 * hash) + MUTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMute());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.audio.Audio.BasicVolumeTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.audio.Audio.BasicVolumeTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.audio.BasicVolumeTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.audio.BasicVolumeTrait)
        weave.trait.audio.Audio.BasicVolumeTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.audio.Audio.BasicVolumeTrait.class, weave.trait.audio.Audio.BasicVolumeTrait.Builder.class);
      }

      // Construct using weave.trait.audio.Audio.BasicVolumeTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        volume_ = 0;

        mute_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.audio.Audio.internal_static_weave_trait_audio_BasicVolumeTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeTrait getDefaultInstanceForType() {
        return weave.trait.audio.Audio.BasicVolumeTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeTrait build() {
        weave.trait.audio.Audio.BasicVolumeTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.audio.Audio.BasicVolumeTrait buildPartial() {
        weave.trait.audio.Audio.BasicVolumeTrait result = new weave.trait.audio.Audio.BasicVolumeTrait(this);
        result.volume_ = volume_;
        result.mute_ = mute_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.audio.Audio.BasicVolumeTrait) {
          return mergeFrom((weave.trait.audio.Audio.BasicVolumeTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.audio.Audio.BasicVolumeTrait other) {
        if (other == weave.trait.audio.Audio.BasicVolumeTrait.getDefaultInstance()) return this;
        if (other.getVolume() != 0) {
          setVolume(other.getVolume());
        }
        if (other.getMute() != false) {
          setMute(other.getMute());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.audio.Audio.BasicVolumeTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.audio.Audio.BasicVolumeTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int volume_ ;
      /**
       * <code>uint32 volume = 1;</code>
       * @return The volume.
       */
      @java.lang.Override
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>uint32 volume = 1;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(int value) {
        
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 volume = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        
        volume_ = 0;
        onChanged();
        return this;
      }

      private boolean mute_ ;
      /**
       * <code>bool mute = 2;</code>
       * @return The mute.
       */
      @java.lang.Override
      public boolean getMute() {
        return mute_;
      }
      /**
       * <code>bool mute = 2;</code>
       * @param value The mute to set.
       * @return This builder for chaining.
       */
      public Builder setMute(boolean value) {
        
        mute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool mute = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMute() {
        
        mute_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.audio.BasicVolumeTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.audio.BasicVolumeTrait)
    private static final weave.trait.audio.Audio.BasicVolumeTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.audio.Audio.BasicVolumeTrait();
    }

    public static weave.trait.audio.Audio.BasicVolumeTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BasicVolumeTrait>
        PARSER = new com.google.protobuf.AbstractParser<BasicVolumeTrait>() {
      @java.lang.Override
      public BasicVolumeTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BasicVolumeTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BasicVolumeTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BasicVolumeTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.audio.Audio.BasicVolumeTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_audio_BasicVolumeTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_audio_BasicVolumeTrait_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027weave/trait/audio.proto\022\021weave.trait.a" +
      "udio\";\n\034BasicVolumeCapabilitiesTrait\022\033\n\023" +
      "volumeSetPointCount\030\001 \001(\r\"0\n\020BasicVolume" +
      "Trait\022\016\n\006volume\030\001 \001(\r\022\014\n\004mute\030\002 \001(\010b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_audio_BasicVolumeCapabilitiesTrait_descriptor,
        new java.lang.String[] { "VolumeSetPointCount", });
    internal_static_weave_trait_audio_BasicVolumeTrait_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weave_trait_audio_BasicVolumeTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_audio_BasicVolumeTrait_descriptor,
        new java.lang.String[] { "Volume", "Mute", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
