// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wdl-event-importance.proto

package wdl;

public final class WdlEventImportance {
  private WdlEventImportance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code wdl.EventImportance}
   */
  public enum EventImportance
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EVENT_IMPORTANCE_UNSPECIFIED = 0;</code>
     */
    EVENT_IMPORTANCE_UNSPECIFIED(0),
    /**
     * <code>EVENT_IMPORTANCE_PRODUCTION_CRITICAL = 1;</code>
     */
    EVENT_IMPORTANCE_PRODUCTION_CRITICAL(1),
    /**
     * <code>EVENT_IMPORTANCE_PRODUCTION_STANDARD = 2;</code>
     */
    EVENT_IMPORTANCE_PRODUCTION_STANDARD(2),
    /**
     * <code>EVENT_IMPORTANCE_INFO = 3;</code>
     */
    EVENT_IMPORTANCE_INFO(3),
    /**
     * <code>EVENT_IMPORTANCE_DEBUG = 4;</code>
     */
    EVENT_IMPORTANCE_DEBUG(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EVENT_IMPORTANCE_UNSPECIFIED = 0;</code>
     */
    public static final int EVENT_IMPORTANCE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>EVENT_IMPORTANCE_PRODUCTION_CRITICAL = 1;</code>
     */
    public static final int EVENT_IMPORTANCE_PRODUCTION_CRITICAL_VALUE = 1;
    /**
     * <code>EVENT_IMPORTANCE_PRODUCTION_STANDARD = 2;</code>
     */
    public static final int EVENT_IMPORTANCE_PRODUCTION_STANDARD_VALUE = 2;
    /**
     * <code>EVENT_IMPORTANCE_INFO = 3;</code>
     */
    public static final int EVENT_IMPORTANCE_INFO_VALUE = 3;
    /**
     * <code>EVENT_IMPORTANCE_DEBUG = 4;</code>
     */
    public static final int EVENT_IMPORTANCE_DEBUG_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventImportance valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventImportance forNumber(int value) {
      switch (value) {
        case 0: return EVENT_IMPORTANCE_UNSPECIFIED;
        case 1: return EVENT_IMPORTANCE_PRODUCTION_CRITICAL;
        case 2: return EVENT_IMPORTANCE_PRODUCTION_STANDARD;
        case 3: return EVENT_IMPORTANCE_INFO;
        case 4: return EVENT_IMPORTANCE_DEBUG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventImportance>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventImportance> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventImportance>() {
            public EventImportance findValueByNumber(int number) {
              return EventImportance.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return wdl.WdlEventImportance.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventImportance[] VALUES = values();

    public static EventImportance valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventImportance(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:wdl.EventImportance)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032wdl-event-importance.proto\022\003wdl*\276\001\n\017Ev" +
      "entImportance\022 \n\034EVENT_IMPORTANCE_UNSPEC" +
      "IFIED\020\000\022(\n$EVENT_IMPORTANCE_PRODUCTION_C" +
      "RITICAL\020\001\022(\n$EVENT_IMPORTANCE_PRODUCTION" +
      "_STANDARD\020\002\022\031\n\025EVENT_IMPORTANCE_INFO\020\003\022\032" +
      "\n\026EVENT_IMPORTANCE_DEBUG\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
