// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weave/trait/peerdevices.proto

package weave.trait.peerdevices;

public final class Peerdevices {
  private Peerdevices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeerDevicesTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.peerdevices.PeerDevicesTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    int getPeerDevicesCount();
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    boolean containsPeerDevices(
        int key);
    /**
     * Use {@link #getPeerDevicesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
    getPeerDevices();
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
    getPeerDevicesMap();
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */

    weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrDefault(
        int key,
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice defaultValue);
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */

    weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code weave.trait.peerdevices.PeerDevicesTrait}
   */
  public static final class PeerDevicesTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.peerdevices.PeerDevicesTrait)
      PeerDevicesTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PeerDevicesTrait.newBuilder() to construct.
    private PeerDevicesTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PeerDevicesTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PeerDevicesTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PeerDevicesTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                peerDevices_ = com.google.protobuf.MapField.newMapField(
                    PeerDevicesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
              peerDevices__ = input.readMessage(
                  PeerDevicesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              peerDevices_.getMutableMap().put(
                  peerDevices__.getKey(), peerDevices__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetPeerDevices();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.class, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.Builder.class);
    }

    public interface PeerDeviceOrBuilder extends
        // @@protoc_insertion_point(interface_extends:weave.trait.peerdevices.PeerDevicesTrait.PeerDevice)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       * @return Whether the deviceId field is set.
       */
      boolean hasDeviceId();
      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       * @return The deviceId.
       */
      weave.common.Common.ResourceId getDeviceId();
      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       */
      weave.common.Common.ResourceIdOrBuilder getDeviceIdOrBuilder();

      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       * @return Whether the resourceTypeName field is set.
       */
      boolean hasResourceTypeName();
      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       * @return The resourceTypeName.
       */
      weave.common.Common.ResourceName getResourceTypeName();
      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       */
      weave.common.Common.ResourceNameOrBuilder getResourceTypeNameOrBuilder();

      /**
       * <code>uint32 vendorId = 3;</code>
       * @return The vendorId.
       */
      int getVendorId();

      /**
       * <code>uint32 productId = 4;</code>
       * @return The productId.
       */
      int getProductId();

      /**
       * <code>string softwareVersion = 5;</code>
       * @return The softwareVersion.
       */
      java.lang.String getSoftwareVersion();
      /**
       * <code>string softwareVersion = 5;</code>
       * @return The bytes for softwareVersion.
       */
      com.google.protobuf.ByteString
          getSoftwareVersionBytes();

      /**
       * <code>bool deviceReady = 6;</code>
       * @return The deviceReady.
       */
      boolean getDeviceReady();
    }
    /**
     * Protobuf type {@code weave.trait.peerdevices.PeerDevicesTrait.PeerDevice}
     */
    public static final class PeerDevice extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:weave.trait.peerdevices.PeerDevicesTrait.PeerDevice)
        PeerDeviceOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PeerDevice.newBuilder() to construct.
      private PeerDevice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PeerDevice() {
        softwareVersion_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PeerDevice();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PeerDevice(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                weave.common.Common.ResourceId.Builder subBuilder = null;
                if (deviceId_ != null) {
                  subBuilder = deviceId_.toBuilder();
                }
                deviceId_ = input.readMessage(weave.common.Common.ResourceId.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(deviceId_);
                  deviceId_ = subBuilder.buildPartial();
                }

                break;
              }
              case 18: {
                weave.common.Common.ResourceName.Builder subBuilder = null;
                if (resourceTypeName_ != null) {
                  subBuilder = resourceTypeName_.toBuilder();
                }
                resourceTypeName_ = input.readMessage(weave.common.Common.ResourceName.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(resourceTypeName_);
                  resourceTypeName_ = subBuilder.buildPartial();
                }

                break;
              }
              case 24: {

                vendorId_ = input.readUInt32();
                break;
              }
              case 32: {

                productId_ = input.readUInt32();
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                softwareVersion_ = s;
                break;
              }
              case 48: {

                deviceReady_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.class, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.Builder.class);
      }

      public static final int DEVICEID_FIELD_NUMBER = 1;
      private weave.common.Common.ResourceId deviceId_;
      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       * @return Whether the deviceId field is set.
       */
      @java.lang.Override
      public boolean hasDeviceId() {
        return deviceId_ != null;
      }
      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       * @return The deviceId.
       */
      @java.lang.Override
      public weave.common.Common.ResourceId getDeviceId() {
        return deviceId_ == null ? weave.common.Common.ResourceId.getDefaultInstance() : deviceId_;
      }
      /**
       * <code>.weave.common.ResourceId deviceId = 1;</code>
       */
      @java.lang.Override
      public weave.common.Common.ResourceIdOrBuilder getDeviceIdOrBuilder() {
        return getDeviceId();
      }

      public static final int RESOURCETYPENAME_FIELD_NUMBER = 2;
      private weave.common.Common.ResourceName resourceTypeName_;
      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       * @return Whether the resourceTypeName field is set.
       */
      @java.lang.Override
      public boolean hasResourceTypeName() {
        return resourceTypeName_ != null;
      }
      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       * @return The resourceTypeName.
       */
      @java.lang.Override
      public weave.common.Common.ResourceName getResourceTypeName() {
        return resourceTypeName_ == null ? weave.common.Common.ResourceName.getDefaultInstance() : resourceTypeName_;
      }
      /**
       * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
       */
      @java.lang.Override
      public weave.common.Common.ResourceNameOrBuilder getResourceTypeNameOrBuilder() {
        return getResourceTypeName();
      }

      public static final int VENDORID_FIELD_NUMBER = 3;
      private int vendorId_;
      /**
       * <code>uint32 vendorId = 3;</code>
       * @return The vendorId.
       */
      @java.lang.Override
      public int getVendorId() {
        return vendorId_;
      }

      public static final int PRODUCTID_FIELD_NUMBER = 4;
      private int productId_;
      /**
       * <code>uint32 productId = 4;</code>
       * @return The productId.
       */
      @java.lang.Override
      public int getProductId() {
        return productId_;
      }

      public static final int SOFTWAREVERSION_FIELD_NUMBER = 5;
      private volatile java.lang.Object softwareVersion_;
      /**
       * <code>string softwareVersion = 5;</code>
       * @return The softwareVersion.
       */
      @java.lang.Override
      public java.lang.String getSoftwareVersion() {
        java.lang.Object ref = softwareVersion_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          softwareVersion_ = s;
          return s;
        }
      }
      /**
       * <code>string softwareVersion = 5;</code>
       * @return The bytes for softwareVersion.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSoftwareVersionBytes() {
        java.lang.Object ref = softwareVersion_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          softwareVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DEVICEREADY_FIELD_NUMBER = 6;
      private boolean deviceReady_;
      /**
       * <code>bool deviceReady = 6;</code>
       * @return The deviceReady.
       */
      @java.lang.Override
      public boolean getDeviceReady() {
        return deviceReady_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (deviceId_ != null) {
          output.writeMessage(1, getDeviceId());
        }
        if (resourceTypeName_ != null) {
          output.writeMessage(2, getResourceTypeName());
        }
        if (vendorId_ != 0) {
          output.writeUInt32(3, vendorId_);
        }
        if (productId_ != 0) {
          output.writeUInt32(4, productId_);
        }
        if (!getSoftwareVersionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, softwareVersion_);
        }
        if (deviceReady_ != false) {
          output.writeBool(6, deviceReady_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (deviceId_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getDeviceId());
        }
        if (resourceTypeName_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getResourceTypeName());
        }
        if (vendorId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(3, vendorId_);
        }
        if (productId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, productId_);
        }
        if (!getSoftwareVersionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, softwareVersion_);
        }
        if (deviceReady_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(6, deviceReady_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice)) {
          return super.equals(obj);
        }
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice other = (weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice) obj;

        if (hasDeviceId() != other.hasDeviceId()) return false;
        if (hasDeviceId()) {
          if (!getDeviceId()
              .equals(other.getDeviceId())) return false;
        }
        if (hasResourceTypeName() != other.hasResourceTypeName()) return false;
        if (hasResourceTypeName()) {
          if (!getResourceTypeName()
              .equals(other.getResourceTypeName())) return false;
        }
        if (getVendorId()
            != other.getVendorId()) return false;
        if (getProductId()
            != other.getProductId()) return false;
        if (!getSoftwareVersion()
            .equals(other.getSoftwareVersion())) return false;
        if (getDeviceReady()
            != other.getDeviceReady()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDeviceId()) {
          hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
          hash = (53 * hash) + getDeviceId().hashCode();
        }
        if (hasResourceTypeName()) {
          hash = (37 * hash) + RESOURCETYPENAME_FIELD_NUMBER;
          hash = (53 * hash) + getResourceTypeName().hashCode();
        }
        hash = (37 * hash) + VENDORID_FIELD_NUMBER;
        hash = (53 * hash) + getVendorId();
        hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
        hash = (53 * hash) + getProductId();
        hash = (37 * hash) + SOFTWAREVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getSoftwareVersion().hashCode();
        hash = (37 * hash) + DEVICEREADY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDeviceReady());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code weave.trait.peerdevices.PeerDevicesTrait.PeerDevice}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:weave.trait.peerdevices.PeerDevicesTrait.PeerDevice)
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDeviceOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.class, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.Builder.class);
        }

        // Construct using weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (deviceIdBuilder_ == null) {
            deviceId_ = null;
          } else {
            deviceId_ = null;
            deviceIdBuilder_ = null;
          }
          if (resourceTypeNameBuilder_ == null) {
            resourceTypeName_ = null;
          } else {
            resourceTypeName_ = null;
            resourceTypeNameBuilder_ = null;
          }
          vendorId_ = 0;

          productId_ = 0;

          softwareVersion_ = "";

          deviceReady_ = false;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor;
        }

        @java.lang.Override
        public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getDefaultInstanceForType() {
          return weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.getDefaultInstance();
        }

        @java.lang.Override
        public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice build() {
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice buildPartial() {
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice result = new weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice(this);
          if (deviceIdBuilder_ == null) {
            result.deviceId_ = deviceId_;
          } else {
            result.deviceId_ = deviceIdBuilder_.build();
          }
          if (resourceTypeNameBuilder_ == null) {
            result.resourceTypeName_ = resourceTypeName_;
          } else {
            result.resourceTypeName_ = resourceTypeNameBuilder_.build();
          }
          result.vendorId_ = vendorId_;
          result.productId_ = productId_;
          result.softwareVersion_ = softwareVersion_;
          result.deviceReady_ = deviceReady_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice) {
            return mergeFrom((weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice other) {
          if (other == weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.getDefaultInstance()) return this;
          if (other.hasDeviceId()) {
            mergeDeviceId(other.getDeviceId());
          }
          if (other.hasResourceTypeName()) {
            mergeResourceTypeName(other.getResourceTypeName());
          }
          if (other.getVendorId() != 0) {
            setVendorId(other.getVendorId());
          }
          if (other.getProductId() != 0) {
            setProductId(other.getProductId());
          }
          if (!other.getSoftwareVersion().isEmpty()) {
            softwareVersion_ = other.softwareVersion_;
            onChanged();
          }
          if (other.getDeviceReady() != false) {
            setDeviceReady(other.getDeviceReady());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private weave.common.Common.ResourceId deviceId_;
        private com.google.protobuf.SingleFieldBuilderV3<
            weave.common.Common.ResourceId, weave.common.Common.ResourceId.Builder, weave.common.Common.ResourceIdOrBuilder> deviceIdBuilder_;
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         * @return Whether the deviceId field is set.
         */
        public boolean hasDeviceId() {
          return deviceIdBuilder_ != null || deviceId_ != null;
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         * @return The deviceId.
         */
        public weave.common.Common.ResourceId getDeviceId() {
          if (deviceIdBuilder_ == null) {
            return deviceId_ == null ? weave.common.Common.ResourceId.getDefaultInstance() : deviceId_;
          } else {
            return deviceIdBuilder_.getMessage();
          }
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public Builder setDeviceId(weave.common.Common.ResourceId value) {
          if (deviceIdBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            deviceId_ = value;
            onChanged();
          } else {
            deviceIdBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public Builder setDeviceId(
            weave.common.Common.ResourceId.Builder builderForValue) {
          if (deviceIdBuilder_ == null) {
            deviceId_ = builderForValue.build();
            onChanged();
          } else {
            deviceIdBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public Builder mergeDeviceId(weave.common.Common.ResourceId value) {
          if (deviceIdBuilder_ == null) {
            if (deviceId_ != null) {
              deviceId_ =
                weave.common.Common.ResourceId.newBuilder(deviceId_).mergeFrom(value).buildPartial();
            } else {
              deviceId_ = value;
            }
            onChanged();
          } else {
            deviceIdBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public Builder clearDeviceId() {
          if (deviceIdBuilder_ == null) {
            deviceId_ = null;
            onChanged();
          } else {
            deviceId_ = null;
            deviceIdBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public weave.common.Common.ResourceId.Builder getDeviceIdBuilder() {
          
          onChanged();
          return getDeviceIdFieldBuilder().getBuilder();
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        public weave.common.Common.ResourceIdOrBuilder getDeviceIdOrBuilder() {
          if (deviceIdBuilder_ != null) {
            return deviceIdBuilder_.getMessageOrBuilder();
          } else {
            return deviceId_ == null ?
                weave.common.Common.ResourceId.getDefaultInstance() : deviceId_;
          }
        }
        /**
         * <code>.weave.common.ResourceId deviceId = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            weave.common.Common.ResourceId, weave.common.Common.ResourceId.Builder, weave.common.Common.ResourceIdOrBuilder> 
            getDeviceIdFieldBuilder() {
          if (deviceIdBuilder_ == null) {
            deviceIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                weave.common.Common.ResourceId, weave.common.Common.ResourceId.Builder, weave.common.Common.ResourceIdOrBuilder>(
                    getDeviceId(),
                    getParentForChildren(),
                    isClean());
            deviceId_ = null;
          }
          return deviceIdBuilder_;
        }

        private weave.common.Common.ResourceName resourceTypeName_;
        private com.google.protobuf.SingleFieldBuilderV3<
            weave.common.Common.ResourceName, weave.common.Common.ResourceName.Builder, weave.common.Common.ResourceNameOrBuilder> resourceTypeNameBuilder_;
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         * @return Whether the resourceTypeName field is set.
         */
        public boolean hasResourceTypeName() {
          return resourceTypeNameBuilder_ != null || resourceTypeName_ != null;
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         * @return The resourceTypeName.
         */
        public weave.common.Common.ResourceName getResourceTypeName() {
          if (resourceTypeNameBuilder_ == null) {
            return resourceTypeName_ == null ? weave.common.Common.ResourceName.getDefaultInstance() : resourceTypeName_;
          } else {
            return resourceTypeNameBuilder_.getMessage();
          }
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public Builder setResourceTypeName(weave.common.Common.ResourceName value) {
          if (resourceTypeNameBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            resourceTypeName_ = value;
            onChanged();
          } else {
            resourceTypeNameBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public Builder setResourceTypeName(
            weave.common.Common.ResourceName.Builder builderForValue) {
          if (resourceTypeNameBuilder_ == null) {
            resourceTypeName_ = builderForValue.build();
            onChanged();
          } else {
            resourceTypeNameBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public Builder mergeResourceTypeName(weave.common.Common.ResourceName value) {
          if (resourceTypeNameBuilder_ == null) {
            if (resourceTypeName_ != null) {
              resourceTypeName_ =
                weave.common.Common.ResourceName.newBuilder(resourceTypeName_).mergeFrom(value).buildPartial();
            } else {
              resourceTypeName_ = value;
            }
            onChanged();
          } else {
            resourceTypeNameBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public Builder clearResourceTypeName() {
          if (resourceTypeNameBuilder_ == null) {
            resourceTypeName_ = null;
            onChanged();
          } else {
            resourceTypeName_ = null;
            resourceTypeNameBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public weave.common.Common.ResourceName.Builder getResourceTypeNameBuilder() {
          
          onChanged();
          return getResourceTypeNameFieldBuilder().getBuilder();
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        public weave.common.Common.ResourceNameOrBuilder getResourceTypeNameOrBuilder() {
          if (resourceTypeNameBuilder_ != null) {
            return resourceTypeNameBuilder_.getMessageOrBuilder();
          } else {
            return resourceTypeName_ == null ?
                weave.common.Common.ResourceName.getDefaultInstance() : resourceTypeName_;
          }
        }
        /**
         * <code>.weave.common.ResourceName resourceTypeName = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            weave.common.Common.ResourceName, weave.common.Common.ResourceName.Builder, weave.common.Common.ResourceNameOrBuilder> 
            getResourceTypeNameFieldBuilder() {
          if (resourceTypeNameBuilder_ == null) {
            resourceTypeNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                weave.common.Common.ResourceName, weave.common.Common.ResourceName.Builder, weave.common.Common.ResourceNameOrBuilder>(
                    getResourceTypeName(),
                    getParentForChildren(),
                    isClean());
            resourceTypeName_ = null;
          }
          return resourceTypeNameBuilder_;
        }

        private int vendorId_ ;
        /**
         * <code>uint32 vendorId = 3;</code>
         * @return The vendorId.
         */
        @java.lang.Override
        public int getVendorId() {
          return vendorId_;
        }
        /**
         * <code>uint32 vendorId = 3;</code>
         * @param value The vendorId to set.
         * @return This builder for chaining.
         */
        public Builder setVendorId(int value) {
          
          vendorId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 vendorId = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearVendorId() {
          
          vendorId_ = 0;
          onChanged();
          return this;
        }

        private int productId_ ;
        /**
         * <code>uint32 productId = 4;</code>
         * @return The productId.
         */
        @java.lang.Override
        public int getProductId() {
          return productId_;
        }
        /**
         * <code>uint32 productId = 4;</code>
         * @param value The productId to set.
         * @return This builder for chaining.
         */
        public Builder setProductId(int value) {
          
          productId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 productId = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearProductId() {
          
          productId_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object softwareVersion_ = "";
        /**
         * <code>string softwareVersion = 5;</code>
         * @return The softwareVersion.
         */
        public java.lang.String getSoftwareVersion() {
          java.lang.Object ref = softwareVersion_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            softwareVersion_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string softwareVersion = 5;</code>
         * @return The bytes for softwareVersion.
         */
        public com.google.protobuf.ByteString
            getSoftwareVersionBytes() {
          java.lang.Object ref = softwareVersion_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            softwareVersion_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string softwareVersion = 5;</code>
         * @param value The softwareVersion to set.
         * @return This builder for chaining.
         */
        public Builder setSoftwareVersion(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          softwareVersion_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string softwareVersion = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearSoftwareVersion() {
          
          softwareVersion_ = getDefaultInstance().getSoftwareVersion();
          onChanged();
          return this;
        }
        /**
         * <code>string softwareVersion = 5;</code>
         * @param value The bytes for softwareVersion to set.
         * @return This builder for chaining.
         */
        public Builder setSoftwareVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          softwareVersion_ = value;
          onChanged();
          return this;
        }

        private boolean deviceReady_ ;
        /**
         * <code>bool deviceReady = 6;</code>
         * @return The deviceReady.
         */
        @java.lang.Override
        public boolean getDeviceReady() {
          return deviceReady_;
        }
        /**
         * <code>bool deviceReady = 6;</code>
         * @param value The deviceReady to set.
         * @return This builder for chaining.
         */
        public Builder setDeviceReady(boolean value) {
          
          deviceReady_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool deviceReady = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearDeviceReady() {
          
          deviceReady_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:weave.trait.peerdevices.PeerDevicesTrait.PeerDevice)
      }

      // @@protoc_insertion_point(class_scope:weave.trait.peerdevices.PeerDevicesTrait.PeerDevice)
      private static final weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice();
      }

      public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PeerDevice>
          PARSER = new com.google.protobuf.AbstractParser<PeerDevice>() {
        @java.lang.Override
        public PeerDevice parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PeerDevice(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PeerDevice> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PeerDevice> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PEERDEVICES_FIELD_NUMBER = 1;
    private static final class PeerDevicesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>newDefaultInstance(
                  weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> peerDevices_;
    private com.google.protobuf.MapField<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
    internalGetPeerDevices() {
      if (peerDevices_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PeerDevicesDefaultEntryHolder.defaultEntry);
      }
      return peerDevices_;
    }

    public int getPeerDevicesCount() {
      return internalGetPeerDevices().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */

    @java.lang.Override
    public boolean containsPeerDevices(
        int key) {
      
      return internalGetPeerDevices().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPeerDevicesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> getPeerDevices() {
      return getPeerDevicesMap();
    }
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> getPeerDevicesMap() {
      return internalGetPeerDevices().getMap();
    }
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    @java.lang.Override

    public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrDefault(
        int key,
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice defaultValue) {
      
      java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> map =
          internalGetPeerDevices().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
     */
    @java.lang.Override

    public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> map =
          internalGetPeerDevices().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetPeerDevices(),
          PeerDevicesDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> entry
           : internalGetPeerDevices().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
        peerDevices__ = PeerDevicesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, peerDevices__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.peerdevices.Peerdevices.PeerDevicesTrait)) {
        return super.equals(obj);
      }
      weave.trait.peerdevices.Peerdevices.PeerDevicesTrait other = (weave.trait.peerdevices.Peerdevices.PeerDevicesTrait) obj;

      if (!internalGetPeerDevices().equals(
          other.internalGetPeerDevices())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetPeerDevices().getMap().isEmpty()) {
        hash = (37 * hash) + PEERDEVICES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPeerDevices().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.peerdevices.Peerdevices.PeerDevicesTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.peerdevices.PeerDevicesTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.peerdevices.PeerDevicesTrait)
        weave.trait.peerdevices.Peerdevices.PeerDevicesTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetPeerDevices();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutablePeerDevices();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.class, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.Builder.class);
      }

      // Construct using weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutablePeerDevices().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.peerdevices.Peerdevices.internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait getDefaultInstanceForType() {
        return weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait build() {
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait buildPartial() {
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait result = new weave.trait.peerdevices.Peerdevices.PeerDevicesTrait(this);
        int from_bitField0_ = bitField0_;
        result.peerDevices_ = internalGetPeerDevices();
        result.peerDevices_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.peerdevices.Peerdevices.PeerDevicesTrait) {
          return mergeFrom((weave.trait.peerdevices.Peerdevices.PeerDevicesTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.peerdevices.Peerdevices.PeerDevicesTrait other) {
        if (other == weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.getDefaultInstance()) return this;
        internalGetMutablePeerDevices().mergeFrom(
            other.internalGetPeerDevices());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.peerdevices.Peerdevices.PeerDevicesTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.peerdevices.Peerdevices.PeerDevicesTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> peerDevices_;
      private com.google.protobuf.MapField<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
      internalGetPeerDevices() {
        if (peerDevices_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PeerDevicesDefaultEntryHolder.defaultEntry);
        }
        return peerDevices_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
      internalGetMutablePeerDevices() {
        onChanged();;
        if (peerDevices_ == null) {
          peerDevices_ = com.google.protobuf.MapField.newMapField(
              PeerDevicesDefaultEntryHolder.defaultEntry);
        }
        if (!peerDevices_.isMutable()) {
          peerDevices_ = peerDevices_.copy();
        }
        return peerDevices_;
      }

      public int getPeerDevicesCount() {
        return internalGetPeerDevices().getMap().size();
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */

      @java.lang.Override
      public boolean containsPeerDevices(
          int key) {
        
        return internalGetPeerDevices().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPeerDevicesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> getPeerDevices() {
        return getPeerDevicesMap();
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> getPeerDevicesMap() {
        return internalGetPeerDevices().getMap();
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */
      @java.lang.Override

      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrDefault(
          int key,
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice defaultValue) {
        
        java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> map =
            internalGetPeerDevices().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */
      @java.lang.Override

      public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice getPeerDevicesOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> map =
            internalGetPeerDevices().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPeerDevices() {
        internalGetMutablePeerDevices().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */

      public Builder removePeerDevices(
          int key) {
        
        internalGetMutablePeerDevices().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice>
      getMutablePeerDevices() {
        return internalGetMutablePeerDevices().getMutableMap();
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */
      public Builder putPeerDevices(
          int key,
          weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePeerDevices().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;uint32, .weave.trait.peerdevices.PeerDevicesTrait.PeerDevice&gt; peerDevices = 1;</code>
       */

      public Builder putAllPeerDevices(
          java.util.Map<java.lang.Integer, weave.trait.peerdevices.Peerdevices.PeerDevicesTrait.PeerDevice> values) {
        internalGetMutablePeerDevices().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.peerdevices.PeerDevicesTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.peerdevices.PeerDevicesTrait)
    private static final weave.trait.peerdevices.Peerdevices.PeerDevicesTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.peerdevices.Peerdevices.PeerDevicesTrait();
    }

    public static weave.trait.peerdevices.Peerdevices.PeerDevicesTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeerDevicesTrait>
        PARSER = new com.google.protobuf.AbstractParser<PeerDevicesTrait>() {
      @java.lang.Override
      public PeerDevicesTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerDevicesTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PeerDevicesTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeerDevicesTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.peerdevices.Peerdevices.PeerDevicesTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_peerdevices_PeerDevicesTrait_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035weave/trait/peerdevices.proto\022\027weave.t" +
      "rait.peerdevices\032\022weave/common.proto\"\221\003\n" +
      "\020PeerDevicesTrait\022O\n\013peerDevices\030\001 \003(\0132:" +
      ".weave.trait.peerdevices.PeerDevicesTrai" +
      "t.PeerDevicesEntry\032h\n\020PeerDevicesEntry\022\013" +
      "\n\003key\030\001 \001(\r\022C\n\005value\030\002 \001(\01324.weave.trait" +
      ".peerdevices.PeerDevicesTrait.PeerDevice" +
      ":\0028\001\032\301\001\n\nPeerDevice\022*\n\010deviceId\030\001 \001(\0132\030." +
      "weave.common.ResourceId\0224\n\020resourceTypeN" +
      "ame\030\002 \001(\0132\032.weave.common.ResourceName\022\020\n" +
      "\010vendorId\030\003 \001(\r\022\021\n\tproductId\030\004 \001(\r\022\027\n\017so" +
      "ftwareVersion\030\005 \001(\t\022\023\n\013deviceReady\030\006 \001(\010" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          weave.common.Common.getDescriptor(),
        });
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor,
        new java.lang.String[] { "PeerDevices", });
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_descriptor =
      internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor.getNestedTypes().get(0);
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevicesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor =
      internal_static_weave_trait_peerdevices_PeerDevicesTrait_descriptor.getNestedTypes().get(1);
    internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_peerdevices_PeerDevicesTrait_PeerDevice_descriptor,
        new java.lang.String[] { "DeviceId", "ResourceTypeName", "VendorId", "ProductId", "SoftwareVersion", "DeviceReady", });
    weave.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
