// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest/trait/promonitoring.proto

package nest.trait.promonitoring;

public final class Promonitoring {
  private Promonitoring() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProMonitoringSettingsTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nest.trait.promonitoring.ProMonitoringSettingsTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
     * @return The enum numeric value on the wire for burglaryMonitoringActivationStatus.
     */
    int getBurglaryMonitoringActivationStatusValue();
    /**
     * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
     * @return The burglaryMonitoringActivationStatus.
     */
    nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus getBurglaryMonitoringActivationStatus();
  }
  /**
   * Protobuf type {@code nest.trait.promonitoring.ProMonitoringSettingsTrait}
   */
  public static final class ProMonitoringSettingsTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nest.trait.promonitoring.ProMonitoringSettingsTrait)
      ProMonitoringSettingsTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProMonitoringSettingsTrait.newBuilder() to construct.
    private ProMonitoringSettingsTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProMonitoringSettingsTrait() {
      burglaryMonitoringActivationStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProMonitoringSettingsTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProMonitoringSettingsTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              burglaryMonitoringActivationStatus_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nest.trait.promonitoring.Promonitoring.internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nest.trait.promonitoring.Promonitoring.internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.class, nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.Builder.class);
    }

    /**
     * Protobuf enum {@code nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus}
     */
    public enum BurglaryMonitoringActivationStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED = 0;</code>
       */
      BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED(0),
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_NOT_ACTIVATED = 1;</code>
       */
      BURGLARY_MONITORING_ACTIVATION_STATUS_NOT_ACTIVATED(1),
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_PENDING = 2;</code>
       */
      BURGLARY_MONITORING_ACTIVATION_STATUS_PENDING(2),
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_ACTIVATED = 3;</code>
       */
      BURGLARY_MONITORING_ACTIVATION_STATUS_ACTIVATED(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED = 0;</code>
       */
      public static final int BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED_VALUE = 0;
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_NOT_ACTIVATED = 1;</code>
       */
      public static final int BURGLARY_MONITORING_ACTIVATION_STATUS_NOT_ACTIVATED_VALUE = 1;
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_PENDING = 2;</code>
       */
      public static final int BURGLARY_MONITORING_ACTIVATION_STATUS_PENDING_VALUE = 2;
      /**
       * <code>BURGLARY_MONITORING_ACTIVATION_STATUS_ACTIVATED = 3;</code>
       */
      public static final int BURGLARY_MONITORING_ACTIVATION_STATUS_ACTIVATED_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BurglaryMonitoringActivationStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static BurglaryMonitoringActivationStatus forNumber(int value) {
        switch (value) {
          case 0: return BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED;
          case 1: return BURGLARY_MONITORING_ACTIVATION_STATUS_NOT_ACTIVATED;
          case 2: return BURGLARY_MONITORING_ACTIVATION_STATUS_PENDING;
          case 3: return BURGLARY_MONITORING_ACTIVATION_STATUS_ACTIVATED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BurglaryMonitoringActivationStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          BurglaryMonitoringActivationStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BurglaryMonitoringActivationStatus>() {
              public BurglaryMonitoringActivationStatus findValueByNumber(int number) {
                return BurglaryMonitoringActivationStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.getDescriptor().getEnumTypes().get(0);
      }

      private static final BurglaryMonitoringActivationStatus[] VALUES = values();

      public static BurglaryMonitoringActivationStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private BurglaryMonitoringActivationStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus)
    }

    public static final int BURGLARYMONITORINGACTIVATIONSTATUS_FIELD_NUMBER = 1;
    private int burglaryMonitoringActivationStatus_;
    /**
     * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
     * @return The enum numeric value on the wire for burglaryMonitoringActivationStatus.
     */
    @java.lang.Override public int getBurglaryMonitoringActivationStatusValue() {
      return burglaryMonitoringActivationStatus_;
    }
    /**
     * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
     * @return The burglaryMonitoringActivationStatus.
     */
    @java.lang.Override public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus getBurglaryMonitoringActivationStatus() {
      @SuppressWarnings("deprecation")
      nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus result = nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.valueOf(burglaryMonitoringActivationStatus_);
      return result == null ? nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (burglaryMonitoringActivationStatus_ != nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED.getNumber()) {
        output.writeEnum(1, burglaryMonitoringActivationStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (burglaryMonitoringActivationStatus_ != nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.BURGLARY_MONITORING_ACTIVATION_STATUS_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, burglaryMonitoringActivationStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait)) {
        return super.equals(obj);
      }
      nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait other = (nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait) obj;

      if (burglaryMonitoringActivationStatus_ != other.burglaryMonitoringActivationStatus_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BURGLARYMONITORINGACTIVATIONSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + burglaryMonitoringActivationStatus_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nest.trait.promonitoring.ProMonitoringSettingsTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nest.trait.promonitoring.ProMonitoringSettingsTrait)
        nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nest.trait.promonitoring.Promonitoring.internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nest.trait.promonitoring.Promonitoring.internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.class, nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.Builder.class);
      }

      // Construct using nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        burglaryMonitoringActivationStatus_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nest.trait.promonitoring.Promonitoring.internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor;
      }

      @java.lang.Override
      public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait getDefaultInstanceForType() {
        return nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.getDefaultInstance();
      }

      @java.lang.Override
      public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait build() {
        nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait buildPartial() {
        nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait result = new nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait(this);
        result.burglaryMonitoringActivationStatus_ = burglaryMonitoringActivationStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait) {
          return mergeFrom((nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait other) {
        if (other == nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.getDefaultInstance()) return this;
        if (other.burglaryMonitoringActivationStatus_ != 0) {
          setBurglaryMonitoringActivationStatusValue(other.getBurglaryMonitoringActivationStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int burglaryMonitoringActivationStatus_ = 0;
      /**
       * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
       * @return The enum numeric value on the wire for burglaryMonitoringActivationStatus.
       */
      @java.lang.Override public int getBurglaryMonitoringActivationStatusValue() {
        return burglaryMonitoringActivationStatus_;
      }
      /**
       * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
       * @param value The enum numeric value on the wire for burglaryMonitoringActivationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBurglaryMonitoringActivationStatusValue(int value) {
        
        burglaryMonitoringActivationStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
       * @return The burglaryMonitoringActivationStatus.
       */
      @java.lang.Override
      public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus getBurglaryMonitoringActivationStatus() {
        @SuppressWarnings("deprecation")
        nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus result = nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.valueOf(burglaryMonitoringActivationStatus_);
        return result == null ? nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
       * @param value The burglaryMonitoringActivationStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBurglaryMonitoringActivationStatus(nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        burglaryMonitoringActivationStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.nest.trait.promonitoring.ProMonitoringSettingsTrait.BurglaryMonitoringActivationStatus burglaryMonitoringActivationStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBurglaryMonitoringActivationStatus() {
        
        burglaryMonitoringActivationStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nest.trait.promonitoring.ProMonitoringSettingsTrait)
    }

    // @@protoc_insertion_point(class_scope:nest.trait.promonitoring.ProMonitoringSettingsTrait)
    private static final nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait();
    }

    public static nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProMonitoringSettingsTrait>
        PARSER = new com.google.protobuf.AbstractParser<ProMonitoringSettingsTrait>() {
      @java.lang.Override
      public ProMonitoringSettingsTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProMonitoringSettingsTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProMonitoringSettingsTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProMonitoringSettingsTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nest.trait.promonitoring.Promonitoring.ProMonitoringSettingsTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036nest/trait/promonitoring.proto\022\030nest.t" +
      "rait.promonitoring\"\241\003\n\032ProMonitoringSett" +
      "ingsTrait\022\203\001\n\"burglaryMonitoringActivati" +
      "onStatus\030\001 \001(\0162W.nest.trait.promonitorin" +
      "g.ProMonitoringSettingsTrait.BurglaryMon" +
      "itoringActivationStatus\"\374\001\n\"BurglaryMoni" +
      "toringActivationStatus\0225\n1BURGLARY_MONIT" +
      "ORING_ACTIVATION_STATUS_UNSPECIFIED\020\000\0227\n" +
      "3BURGLARY_MONITORING_ACTIVATION_STATUS_N" +
      "OT_ACTIVATED\020\001\0221\n-BURGLARY_MONITORING_AC" +
      "TIVATION_STATUS_PENDING\020\002\0223\n/BURGLARY_MO" +
      "NITORING_ACTIVATION_STATUS_ACTIVATED\020\003b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nest_trait_promonitoring_ProMonitoringSettingsTrait_descriptor,
        new java.lang.String[] { "BurglaryMonitoringActivationStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
