// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest/trait/olive.proto

package nest.trait.olive;

public final class Olive {
  private Olive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GaiaMergeNotificationsTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nest.trait.olive.GaiaMergeNotificationsTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    int getStructureInvitationsCount();
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    boolean containsStructureInvitations(
        java.lang.String key);
    /**
     * Use {@link #getStructureInvitationsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
    getStructureInvitations();
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
    getStructureInvitationsMap();
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */

    nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrDefault(
        java.lang.String key,
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation defaultValue);
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */

    nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrThrow(
        java.lang.String key);

    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     * @return Whether the latestUserGaiaMergeNotified field is set.
     */
    boolean hasLatestUserGaiaMergeNotified();
    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     * @return The latestUserGaiaMergeNotified.
     */
    com.google.protobuf.Timestamp getLatestUserGaiaMergeNotified();
    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLatestUserGaiaMergeNotifiedOrBuilder();
  }
  /**
   * Protobuf type {@code nest.trait.olive.GaiaMergeNotificationsTrait}
   */
  public static final class GaiaMergeNotificationsTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nest.trait.olive.GaiaMergeNotificationsTrait)
      GaiaMergeNotificationsTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GaiaMergeNotificationsTrait.newBuilder() to construct.
    private GaiaMergeNotificationsTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GaiaMergeNotificationsTrait() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GaiaMergeNotificationsTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GaiaMergeNotificationsTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                structureInvitations_ = com.google.protobuf.MapField.newMapField(
                    StructureInvitationsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
              structureInvitations__ = input.readMessage(
                  StructureInvitationsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              structureInvitations_.getMutableMap().put(
                  structureInvitations__.getKey(), structureInvitations__.getValue());
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (latestUserGaiaMergeNotified_ != null) {
                subBuilder = latestUserGaiaMergeNotified_.toBuilder();
              }
              latestUserGaiaMergeNotified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(latestUserGaiaMergeNotified_);
                latestUserGaiaMergeNotified_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetStructureInvitations();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nest.trait.olive.Olive.GaiaMergeNotificationsTrait.class, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.Builder.class);
    }

    public interface StructureInvitationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       * @return Whether the latestStructureInviteNotified field is set.
       */
      boolean hasLatestStructureInviteNotified();
      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       * @return The latestStructureInviteNotified.
       */
      com.google.protobuf.Timestamp getLatestStructureInviteNotified();
      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       */
      com.google.protobuf.TimestampOrBuilder getLatestStructureInviteNotifiedOrBuilder();

      /**
       * <code>string invitationToken = 2;</code>
       * @return The invitationToken.
       */
      java.lang.String getInvitationToken();
      /**
       * <code>string invitationToken = 2;</code>
       * @return The bytes for invitationToken.
       */
      com.google.protobuf.ByteString
          getInvitationTokenBytes();
    }
    /**
     * Protobuf type {@code nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation}
     */
    public static final class StructureInvitation extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation)
        StructureInvitationOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use StructureInvitation.newBuilder() to construct.
      private StructureInvitation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private StructureInvitation() {
        invitationToken_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new StructureInvitation();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private StructureInvitation(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.Timestamp.Builder subBuilder = null;
                if (latestStructureInviteNotified_ != null) {
                  subBuilder = latestStructureInviteNotified_.toBuilder();
                }
                latestStructureInviteNotified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(latestStructureInviteNotified_);
                  latestStructureInviteNotified_ = subBuilder.buildPartial();
                }

                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                invitationToken_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.class, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.Builder.class);
      }

      public static final int LATESTSTRUCTUREINVITENOTIFIED_FIELD_NUMBER = 1;
      private com.google.protobuf.Timestamp latestStructureInviteNotified_;
      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       * @return Whether the latestStructureInviteNotified field is set.
       */
      @java.lang.Override
      public boolean hasLatestStructureInviteNotified() {
        return latestStructureInviteNotified_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       * @return The latestStructureInviteNotified.
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getLatestStructureInviteNotified() {
        return latestStructureInviteNotified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : latestStructureInviteNotified_;
      }
      /**
       * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.TimestampOrBuilder getLatestStructureInviteNotifiedOrBuilder() {
        return getLatestStructureInviteNotified();
      }

      public static final int INVITATIONTOKEN_FIELD_NUMBER = 2;
      private volatile java.lang.Object invitationToken_;
      /**
       * <code>string invitationToken = 2;</code>
       * @return The invitationToken.
       */
      @java.lang.Override
      public java.lang.String getInvitationToken() {
        java.lang.Object ref = invitationToken_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          invitationToken_ = s;
          return s;
        }
      }
      /**
       * <code>string invitationToken = 2;</code>
       * @return The bytes for invitationToken.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getInvitationTokenBytes() {
        java.lang.Object ref = invitationToken_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          invitationToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (latestStructureInviteNotified_ != null) {
          output.writeMessage(1, getLatestStructureInviteNotified());
        }
        if (!getInvitationTokenBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, invitationToken_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (latestStructureInviteNotified_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getLatestStructureInviteNotified());
        }
        if (!getInvitationTokenBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, invitationToken_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation)) {
          return super.equals(obj);
        }
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation other = (nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation) obj;

        if (hasLatestStructureInviteNotified() != other.hasLatestStructureInviteNotified()) return false;
        if (hasLatestStructureInviteNotified()) {
          if (!getLatestStructureInviteNotified()
              .equals(other.getLatestStructureInviteNotified())) return false;
        }
        if (!getInvitationToken()
            .equals(other.getInvitationToken())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasLatestStructureInviteNotified()) {
          hash = (37 * hash) + LATESTSTRUCTUREINVITENOTIFIED_FIELD_NUMBER;
          hash = (53 * hash) + getLatestStructureInviteNotified().hashCode();
        }
        hash = (37 * hash) + INVITATIONTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getInvitationToken().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation)
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.class, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.Builder.class);
        }

        // Construct using nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (latestStructureInviteNotifiedBuilder_ == null) {
            latestStructureInviteNotified_ = null;
          } else {
            latestStructureInviteNotified_ = null;
            latestStructureInviteNotifiedBuilder_ = null;
          }
          invitationToken_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor;
        }

        @java.lang.Override
        public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getDefaultInstanceForType() {
          return nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.getDefaultInstance();
        }

        @java.lang.Override
        public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation build() {
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation buildPartial() {
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation result = new nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation(this);
          if (latestStructureInviteNotifiedBuilder_ == null) {
            result.latestStructureInviteNotified_ = latestStructureInviteNotified_;
          } else {
            result.latestStructureInviteNotified_ = latestStructureInviteNotifiedBuilder_.build();
          }
          result.invitationToken_ = invitationToken_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation) {
            return mergeFrom((nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation other) {
          if (other == nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.getDefaultInstance()) return this;
          if (other.hasLatestStructureInviteNotified()) {
            mergeLatestStructureInviteNotified(other.getLatestStructureInviteNotified());
          }
          if (!other.getInvitationToken().isEmpty()) {
            invitationToken_ = other.invitationToken_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.Timestamp latestStructureInviteNotified_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> latestStructureInviteNotifiedBuilder_;
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         * @return Whether the latestStructureInviteNotified field is set.
         */
        public boolean hasLatestStructureInviteNotified() {
          return latestStructureInviteNotifiedBuilder_ != null || latestStructureInviteNotified_ != null;
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         * @return The latestStructureInviteNotified.
         */
        public com.google.protobuf.Timestamp getLatestStructureInviteNotified() {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            return latestStructureInviteNotified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : latestStructureInviteNotified_;
          } else {
            return latestStructureInviteNotifiedBuilder_.getMessage();
          }
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public Builder setLatestStructureInviteNotified(com.google.protobuf.Timestamp value) {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            latestStructureInviteNotified_ = value;
            onChanged();
          } else {
            latestStructureInviteNotifiedBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public Builder setLatestStructureInviteNotified(
            com.google.protobuf.Timestamp.Builder builderForValue) {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            latestStructureInviteNotified_ = builderForValue.build();
            onChanged();
          } else {
            latestStructureInviteNotifiedBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public Builder mergeLatestStructureInviteNotified(com.google.protobuf.Timestamp value) {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            if (latestStructureInviteNotified_ != null) {
              latestStructureInviteNotified_ =
                com.google.protobuf.Timestamp.newBuilder(latestStructureInviteNotified_).mergeFrom(value).buildPartial();
            } else {
              latestStructureInviteNotified_ = value;
            }
            onChanged();
          } else {
            latestStructureInviteNotifiedBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public Builder clearLatestStructureInviteNotified() {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            latestStructureInviteNotified_ = null;
            onChanged();
          } else {
            latestStructureInviteNotified_ = null;
            latestStructureInviteNotifiedBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public com.google.protobuf.Timestamp.Builder getLatestStructureInviteNotifiedBuilder() {
          
          onChanged();
          return getLatestStructureInviteNotifiedFieldBuilder().getBuilder();
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getLatestStructureInviteNotifiedOrBuilder() {
          if (latestStructureInviteNotifiedBuilder_ != null) {
            return latestStructureInviteNotifiedBuilder_.getMessageOrBuilder();
          } else {
            return latestStructureInviteNotified_ == null ?
                com.google.protobuf.Timestamp.getDefaultInstance() : latestStructureInviteNotified_;
          }
        }
        /**
         * <code>.google.protobuf.Timestamp latestStructureInviteNotified = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
            getLatestStructureInviteNotifiedFieldBuilder() {
          if (latestStructureInviteNotifiedBuilder_ == null) {
            latestStructureInviteNotifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                    getLatestStructureInviteNotified(),
                    getParentForChildren(),
                    isClean());
            latestStructureInviteNotified_ = null;
          }
          return latestStructureInviteNotifiedBuilder_;
        }

        private java.lang.Object invitationToken_ = "";
        /**
         * <code>string invitationToken = 2;</code>
         * @return The invitationToken.
         */
        public java.lang.String getInvitationToken() {
          java.lang.Object ref = invitationToken_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            invitationToken_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string invitationToken = 2;</code>
         * @return The bytes for invitationToken.
         */
        public com.google.protobuf.ByteString
            getInvitationTokenBytes() {
          java.lang.Object ref = invitationToken_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            invitationToken_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string invitationToken = 2;</code>
         * @param value The invitationToken to set.
         * @return This builder for chaining.
         */
        public Builder setInvitationToken(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          invitationToken_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string invitationToken = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearInvitationToken() {
          
          invitationToken_ = getDefaultInstance().getInvitationToken();
          onChanged();
          return this;
        }
        /**
         * <code>string invitationToken = 2;</code>
         * @param value The bytes for invitationToken to set.
         * @return This builder for chaining.
         */
        public Builder setInvitationTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          invitationToken_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation)
      }

      // @@protoc_insertion_point(class_scope:nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation)
      private static final nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation();
      }

      public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<StructureInvitation>
          PARSER = new com.google.protobuf.AbstractParser<StructureInvitation>() {
        @java.lang.Override
        public StructureInvitation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new StructureInvitation(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<StructureInvitation> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<StructureInvitation> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STRUCTUREINVITATIONS_FIELD_NUMBER = 1;
    private static final class StructureInvitationsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>newDefaultInstance(
                  nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> structureInvitations_;
    private com.google.protobuf.MapField<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
    internalGetStructureInvitations() {
      if (structureInvitations_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StructureInvitationsDefaultEntryHolder.defaultEntry);
      }
      return structureInvitations_;
    }

    public int getStructureInvitationsCount() {
      return internalGetStructureInvitations().getMap().size();
    }
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */

    @java.lang.Override
    public boolean containsStructureInvitations(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetStructureInvitations().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStructureInvitationsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> getStructureInvitations() {
      return getStructureInvitationsMap();
    }
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> getStructureInvitationsMap() {
      return internalGetStructureInvitations().getMap();
    }
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    @java.lang.Override

    public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrDefault(
        java.lang.String key,
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> map =
          internalGetStructureInvitations().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
     */
    @java.lang.Override

    public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> map =
          internalGetStructureInvitations().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LATESTUSERGAIAMERGENOTIFIED_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp latestUserGaiaMergeNotified_;
    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     * @return Whether the latestUserGaiaMergeNotified field is set.
     */
    @java.lang.Override
    public boolean hasLatestUserGaiaMergeNotified() {
      return latestUserGaiaMergeNotified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     * @return The latestUserGaiaMergeNotified.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLatestUserGaiaMergeNotified() {
      return latestUserGaiaMergeNotified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : latestUserGaiaMergeNotified_;
    }
    /**
     * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLatestUserGaiaMergeNotifiedOrBuilder() {
      return getLatestUserGaiaMergeNotified();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStructureInvitations(),
          StructureInvitationsDefaultEntryHolder.defaultEntry,
          1);
      if (latestUserGaiaMergeNotified_ != null) {
        output.writeMessage(2, getLatestUserGaiaMergeNotified());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> entry
           : internalGetStructureInvitations().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
        structureInvitations__ = StructureInvitationsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, structureInvitations__);
      }
      if (latestUserGaiaMergeNotified_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLatestUserGaiaMergeNotified());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nest.trait.olive.Olive.GaiaMergeNotificationsTrait)) {
        return super.equals(obj);
      }
      nest.trait.olive.Olive.GaiaMergeNotificationsTrait other = (nest.trait.olive.Olive.GaiaMergeNotificationsTrait) obj;

      if (!internalGetStructureInvitations().equals(
          other.internalGetStructureInvitations())) return false;
      if (hasLatestUserGaiaMergeNotified() != other.hasLatestUserGaiaMergeNotified()) return false;
      if (hasLatestUserGaiaMergeNotified()) {
        if (!getLatestUserGaiaMergeNotified()
            .equals(other.getLatestUserGaiaMergeNotified())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetStructureInvitations().getMap().isEmpty()) {
        hash = (37 * hash) + STRUCTUREINVITATIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStructureInvitations().hashCode();
      }
      if (hasLatestUserGaiaMergeNotified()) {
        hash = (37 * hash) + LATESTUSERGAIAMERGENOTIFIED_FIELD_NUMBER;
        hash = (53 * hash) + getLatestUserGaiaMergeNotified().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nest.trait.olive.Olive.GaiaMergeNotificationsTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nest.trait.olive.GaiaMergeNotificationsTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nest.trait.olive.GaiaMergeNotificationsTrait)
        nest.trait.olive.Olive.GaiaMergeNotificationsTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetStructureInvitations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableStructureInvitations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nest.trait.olive.Olive.GaiaMergeNotificationsTrait.class, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.Builder.class);
      }

      // Construct using nest.trait.olive.Olive.GaiaMergeNotificationsTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableStructureInvitations().clear();
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          latestUserGaiaMergeNotified_ = null;
        } else {
          latestUserGaiaMergeNotified_ = null;
          latestUserGaiaMergeNotifiedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nest.trait.olive.Olive.internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor;
      }

      @java.lang.Override
      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait getDefaultInstanceForType() {
        return nest.trait.olive.Olive.GaiaMergeNotificationsTrait.getDefaultInstance();
      }

      @java.lang.Override
      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait build() {
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait buildPartial() {
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait result = new nest.trait.olive.Olive.GaiaMergeNotificationsTrait(this);
        int from_bitField0_ = bitField0_;
        result.structureInvitations_ = internalGetStructureInvitations();
        result.structureInvitations_.makeImmutable();
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          result.latestUserGaiaMergeNotified_ = latestUserGaiaMergeNotified_;
        } else {
          result.latestUserGaiaMergeNotified_ = latestUserGaiaMergeNotifiedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nest.trait.olive.Olive.GaiaMergeNotificationsTrait) {
          return mergeFrom((nest.trait.olive.Olive.GaiaMergeNotificationsTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nest.trait.olive.Olive.GaiaMergeNotificationsTrait other) {
        if (other == nest.trait.olive.Olive.GaiaMergeNotificationsTrait.getDefaultInstance()) return this;
        internalGetMutableStructureInvitations().mergeFrom(
            other.internalGetStructureInvitations());
        if (other.hasLatestUserGaiaMergeNotified()) {
          mergeLatestUserGaiaMergeNotified(other.getLatestUserGaiaMergeNotified());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nest.trait.olive.Olive.GaiaMergeNotificationsTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nest.trait.olive.Olive.GaiaMergeNotificationsTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> structureInvitations_;
      private com.google.protobuf.MapField<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
      internalGetStructureInvitations() {
        if (structureInvitations_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StructureInvitationsDefaultEntryHolder.defaultEntry);
        }
        return structureInvitations_;
      }
      private com.google.protobuf.MapField<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
      internalGetMutableStructureInvitations() {
        onChanged();;
        if (structureInvitations_ == null) {
          structureInvitations_ = com.google.protobuf.MapField.newMapField(
              StructureInvitationsDefaultEntryHolder.defaultEntry);
        }
        if (!structureInvitations_.isMutable()) {
          structureInvitations_ = structureInvitations_.copy();
        }
        return structureInvitations_;
      }

      public int getStructureInvitationsCount() {
        return internalGetStructureInvitations().getMap().size();
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */

      @java.lang.Override
      public boolean containsStructureInvitations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStructureInvitations().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStructureInvitationsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> getStructureInvitations() {
        return getStructureInvitationsMap();
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> getStructureInvitationsMap() {
        return internalGetStructureInvitations().getMap();
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */
      @java.lang.Override

      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrDefault(
          java.lang.String key,
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> map =
            internalGetStructureInvitations().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */
      @java.lang.Override

      public nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation getStructureInvitationsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> map =
            internalGetStructureInvitations().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStructureInvitations() {
        internalGetMutableStructureInvitations().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */

      public Builder removeStructureInvitations(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStructureInvitations().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation>
      getMutableStructureInvitations() {
        return internalGetMutableStructureInvitations().getMutableMap();
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */
      public Builder putStructureInvitations(
          java.lang.String key,
          nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStructureInvitations().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .nest.trait.olive.GaiaMergeNotificationsTrait.StructureInvitation&gt; structureInvitations = 1;</code>
       */

      public Builder putAllStructureInvitations(
          java.util.Map<java.lang.String, nest.trait.olive.Olive.GaiaMergeNotificationsTrait.StructureInvitation> values) {
        internalGetMutableStructureInvitations().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.Timestamp latestUserGaiaMergeNotified_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> latestUserGaiaMergeNotifiedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       * @return Whether the latestUserGaiaMergeNotified field is set.
       */
      public boolean hasLatestUserGaiaMergeNotified() {
        return latestUserGaiaMergeNotifiedBuilder_ != null || latestUserGaiaMergeNotified_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       * @return The latestUserGaiaMergeNotified.
       */
      public com.google.protobuf.Timestamp getLatestUserGaiaMergeNotified() {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          return latestUserGaiaMergeNotified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : latestUserGaiaMergeNotified_;
        } else {
          return latestUserGaiaMergeNotifiedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public Builder setLatestUserGaiaMergeNotified(com.google.protobuf.Timestamp value) {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          latestUserGaiaMergeNotified_ = value;
          onChanged();
        } else {
          latestUserGaiaMergeNotifiedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public Builder setLatestUserGaiaMergeNotified(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          latestUserGaiaMergeNotified_ = builderForValue.build();
          onChanged();
        } else {
          latestUserGaiaMergeNotifiedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public Builder mergeLatestUserGaiaMergeNotified(com.google.protobuf.Timestamp value) {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          if (latestUserGaiaMergeNotified_ != null) {
            latestUserGaiaMergeNotified_ =
              com.google.protobuf.Timestamp.newBuilder(latestUserGaiaMergeNotified_).mergeFrom(value).buildPartial();
          } else {
            latestUserGaiaMergeNotified_ = value;
          }
          onChanged();
        } else {
          latestUserGaiaMergeNotifiedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public Builder clearLatestUserGaiaMergeNotified() {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          latestUserGaiaMergeNotified_ = null;
          onChanged();
        } else {
          latestUserGaiaMergeNotified_ = null;
          latestUserGaiaMergeNotifiedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLatestUserGaiaMergeNotifiedBuilder() {
        
        onChanged();
        return getLatestUserGaiaMergeNotifiedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLatestUserGaiaMergeNotifiedOrBuilder() {
        if (latestUserGaiaMergeNotifiedBuilder_ != null) {
          return latestUserGaiaMergeNotifiedBuilder_.getMessageOrBuilder();
        } else {
          return latestUserGaiaMergeNotified_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : latestUserGaiaMergeNotified_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp latestUserGaiaMergeNotified = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLatestUserGaiaMergeNotifiedFieldBuilder() {
        if (latestUserGaiaMergeNotifiedBuilder_ == null) {
          latestUserGaiaMergeNotifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLatestUserGaiaMergeNotified(),
                  getParentForChildren(),
                  isClean());
          latestUserGaiaMergeNotified_ = null;
        }
        return latestUserGaiaMergeNotifiedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nest.trait.olive.GaiaMergeNotificationsTrait)
    }

    // @@protoc_insertion_point(class_scope:nest.trait.olive.GaiaMergeNotificationsTrait)
    private static final nest.trait.olive.Olive.GaiaMergeNotificationsTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nest.trait.olive.Olive.GaiaMergeNotificationsTrait();
    }

    public static nest.trait.olive.Olive.GaiaMergeNotificationsTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GaiaMergeNotificationsTrait>
        PARSER = new com.google.protobuf.AbstractParser<GaiaMergeNotificationsTrait>() {
      @java.lang.Override
      public GaiaMergeNotificationsTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GaiaMergeNotificationsTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GaiaMergeNotificationsTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GaiaMergeNotificationsTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nest.trait.olive.Olive.GaiaMergeNotificationsTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026nest/trait/olive.proto\022\020nest.trait.oli" +
      "ve\032\037google/protobuf/timestamp.proto\"\270\003\n\033" +
      "GaiaMergeNotificationsTrait\022e\n\024structure" +
      "Invitations\030\001 \003(\0132G.nest.trait.olive.Gai" +
      "aMergeNotificationsTrait.StructureInvita" +
      "tionsEntry\022?\n\033latestUserGaiaMergeNotifie" +
      "d\030\002 \001(\0132\032.google.protobuf.Timestamp\032~\n\031S" +
      "tructureInvitationsEntry\022\013\n\003key\030\001 \001(\t\022P\n" +
      "\005value\030\002 \001(\0132A.nest.trait.olive.GaiaMerg" +
      "eNotificationsTrait.StructureInvitation:" +
      "\0028\001\032q\n\023StructureInvitation\022A\n\035latestStru" +
      "ctureInviteNotified\030\001 \001(\0132\032.google.proto" +
      "buf.Timestamp\022\027\n\017invitationToken\030\002 \001(\tb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor,
        new java.lang.String[] { "StructureInvitations", "LatestUserGaiaMergeNotified", });
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_descriptor =
      internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor.getNestedTypes().get(0);
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor =
      internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_descriptor.getNestedTypes().get(1);
    internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nest_trait_olive_GaiaMergeNotificationsTrait_StructureInvitation_descriptor,
        new java.lang.String[] { "LatestStructureInviteNotified", "InvitationToken", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
