// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weave/trait/network.proto

package weave.trait.network;

public final class Network {
  private Network() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetworkInterfaceCapabilityTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.network.NetworkInterfaceCapabilityTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
     * @return The type.
     */
    weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType getType();

    /**
     * <code>.weave.common.StringRef description = 2;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <code>.weave.common.StringRef description = 2;</code>
     * @return The description.
     */
    weave.common.Common.StringRef getDescription();
    /**
     * <code>.weave.common.StringRef description = 2;</code>
     */
    weave.common.Common.StringRefOrBuilder getDescriptionOrBuilder();
  }
  /**
   * Protobuf type {@code weave.trait.network.NetworkInterfaceCapabilityTrait}
   */
  public static final class NetworkInterfaceCapabilityTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.network.NetworkInterfaceCapabilityTrait)
      NetworkInterfaceCapabilityTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkInterfaceCapabilityTrait.newBuilder() to construct.
    private NetworkInterfaceCapabilityTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkInterfaceCapabilityTrait() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkInterfaceCapabilityTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkInterfaceCapabilityTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              weave.common.Common.StringRef.Builder subBuilder = null;
              if (description_ != null) {
                subBuilder = description_.toBuilder();
              }
              description_ = input.readMessage(weave.common.Common.StringRef.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(description_);
                description_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.network.Network.NetworkInterfaceCapabilityTrait.class, weave.trait.network.Network.NetworkInterfaceCapabilityTrait.Builder.class);
    }

    /**
     * Protobuf enum {@code weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType}
     */
    public enum NetworkInterfaceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NETWORK_INTERFACE_TYPE_UNSPECIFIED = 0;</code>
       */
      NETWORK_INTERFACE_TYPE_UNSPECIFIED(0),
      /**
       * <code>NETWORK_INTERFACE_TYPE_WEAVE_TUNNEL = 1;</code>
       */
      NETWORK_INTERFACE_TYPE_WEAVE_TUNNEL(1),
      /**
       * <code>NETWORK_INTERFACE_TYPE_WIFI = 2;</code>
       */
      NETWORK_INTERFACE_TYPE_WIFI(2),
      /**
       * <code>NETWORK_INTERFACE_TYPE_THREAD = 3;</code>
       */
      NETWORK_INTERFACE_TYPE_THREAD(3),
      /**
       * <code>NETWORK_INTERFACE_TYPE_CELLULAR = 4;</code>
       */
      NETWORK_INTERFACE_TYPE_CELLULAR(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NETWORK_INTERFACE_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int NETWORK_INTERFACE_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>NETWORK_INTERFACE_TYPE_WEAVE_TUNNEL = 1;</code>
       */
      public static final int NETWORK_INTERFACE_TYPE_WEAVE_TUNNEL_VALUE = 1;
      /**
       * <code>NETWORK_INTERFACE_TYPE_WIFI = 2;</code>
       */
      public static final int NETWORK_INTERFACE_TYPE_WIFI_VALUE = 2;
      /**
       * <code>NETWORK_INTERFACE_TYPE_THREAD = 3;</code>
       */
      public static final int NETWORK_INTERFACE_TYPE_THREAD_VALUE = 3;
      /**
       * <code>NETWORK_INTERFACE_TYPE_CELLULAR = 4;</code>
       */
      public static final int NETWORK_INTERFACE_TYPE_CELLULAR_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NetworkInterfaceType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static NetworkInterfaceType forNumber(int value) {
        switch (value) {
          case 0: return NETWORK_INTERFACE_TYPE_UNSPECIFIED;
          case 1: return NETWORK_INTERFACE_TYPE_WEAVE_TUNNEL;
          case 2: return NETWORK_INTERFACE_TYPE_WIFI;
          case 3: return NETWORK_INTERFACE_TYPE_THREAD;
          case 4: return NETWORK_INTERFACE_TYPE_CELLULAR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NetworkInterfaceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NetworkInterfaceType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetworkInterfaceType>() {
              public NetworkInterfaceType findValueByNumber(int number) {
                return NetworkInterfaceType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return weave.trait.network.Network.NetworkInterfaceCapabilityTrait.getDescriptor().getEnumTypes().get(0);
      }

      private static final NetworkInterfaceType[] VALUES = values();

      public static NetworkInterfaceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NetworkInterfaceType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType getType() {
      @SuppressWarnings("deprecation")
      weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType result = weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.valueOf(type_);
      return result == null ? weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.UNRECOGNIZED : result;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private weave.common.Common.StringRef description_;
    /**
     * <code>.weave.common.StringRef description = 2;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return description_ != null;
    }
    /**
     * <code>.weave.common.StringRef description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public weave.common.Common.StringRef getDescription() {
      return description_ == null ? weave.common.Common.StringRef.getDefaultInstance() : description_;
    }
    /**
     * <code>.weave.common.StringRef description = 2;</code>
     */
    @java.lang.Override
    public weave.common.Common.StringRefOrBuilder getDescriptionOrBuilder() {
      return getDescription();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.NETWORK_INTERFACE_TYPE_UNSPECIFIED.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (description_ != null) {
        output.writeMessage(2, getDescription());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.NETWORK_INTERFACE_TYPE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (description_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDescription());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.network.Network.NetworkInterfaceCapabilityTrait)) {
        return super.equals(obj);
      }
      weave.trait.network.Network.NetworkInterfaceCapabilityTrait other = (weave.trait.network.Network.NetworkInterfaceCapabilityTrait) obj;

      if (type_ != other.type_) return false;
      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.network.Network.NetworkInterfaceCapabilityTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.network.NetworkInterfaceCapabilityTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.network.NetworkInterfaceCapabilityTrait)
        weave.trait.network.Network.NetworkInterfaceCapabilityTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.network.Network.NetworkInterfaceCapabilityTrait.class, weave.trait.network.Network.NetworkInterfaceCapabilityTrait.Builder.class);
      }

      // Construct using weave.trait.network.Network.NetworkInterfaceCapabilityTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (descriptionBuilder_ == null) {
          description_ = null;
        } else {
          description_ = null;
          descriptionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceCapabilityTrait getDefaultInstanceForType() {
        return weave.trait.network.Network.NetworkInterfaceCapabilityTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceCapabilityTrait build() {
        weave.trait.network.Network.NetworkInterfaceCapabilityTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceCapabilityTrait buildPartial() {
        weave.trait.network.Network.NetworkInterfaceCapabilityTrait result = new weave.trait.network.Network.NetworkInterfaceCapabilityTrait(this);
        result.type_ = type_;
        if (descriptionBuilder_ == null) {
          result.description_ = description_;
        } else {
          result.description_ = descriptionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.network.Network.NetworkInterfaceCapabilityTrait) {
          return mergeFrom((weave.trait.network.Network.NetworkInterfaceCapabilityTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.network.Network.NetworkInterfaceCapabilityTrait other) {
        if (other == weave.trait.network.Network.NetworkInterfaceCapabilityTrait.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasDescription()) {
          mergeDescription(other.getDescription());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.network.Network.NetworkInterfaceCapabilityTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.network.Network.NetworkInterfaceCapabilityTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType getType() {
        @SuppressWarnings("deprecation")
        weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType result = weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.valueOf(type_);
        return result == null ? weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType.UNRECOGNIZED : result;
      }
      /**
       * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(weave.trait.network.Network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.weave.trait.network.NetworkInterfaceCapabilityTrait.NetworkInterfaceType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private weave.common.Common.StringRef description_;
      private com.google.protobuf.SingleFieldBuilderV3<
          weave.common.Common.StringRef, weave.common.Common.StringRef.Builder, weave.common.Common.StringRefOrBuilder> descriptionBuilder_;
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return descriptionBuilder_ != null || description_ != null;
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       * @return The description.
       */
      public weave.common.Common.StringRef getDescription() {
        if (descriptionBuilder_ == null) {
          return description_ == null ? weave.common.Common.StringRef.getDefaultInstance() : description_;
        } else {
          return descriptionBuilder_.getMessage();
        }
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public Builder setDescription(weave.common.Common.StringRef value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          description_ = value;
          onChanged();
        } else {
          descriptionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public Builder setDescription(
          weave.common.Common.StringRef.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          description_ = builderForValue.build();
          onChanged();
        } else {
          descriptionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public Builder mergeDescription(weave.common.Common.StringRef value) {
        if (descriptionBuilder_ == null) {
          if (description_ != null) {
            description_ =
              weave.common.Common.StringRef.newBuilder(description_).mergeFrom(value).buildPartial();
          } else {
            description_ = value;
          }
          onChanged();
        } else {
          descriptionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public Builder clearDescription() {
        if (descriptionBuilder_ == null) {
          description_ = null;
          onChanged();
        } else {
          description_ = null;
          descriptionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public weave.common.Common.StringRef.Builder getDescriptionBuilder() {
        
        onChanged();
        return getDescriptionFieldBuilder().getBuilder();
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      public weave.common.Common.StringRefOrBuilder getDescriptionOrBuilder() {
        if (descriptionBuilder_ != null) {
          return descriptionBuilder_.getMessageOrBuilder();
        } else {
          return description_ == null ?
              weave.common.Common.StringRef.getDefaultInstance() : description_;
        }
      }
      /**
       * <code>.weave.common.StringRef description = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          weave.common.Common.StringRef, weave.common.Common.StringRef.Builder, weave.common.Common.StringRefOrBuilder> 
          getDescriptionFieldBuilder() {
        if (descriptionBuilder_ == null) {
          descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              weave.common.Common.StringRef, weave.common.Common.StringRef.Builder, weave.common.Common.StringRefOrBuilder>(
                  getDescription(),
                  getParentForChildren(),
                  isClean());
          description_ = null;
        }
        return descriptionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.network.NetworkInterfaceCapabilityTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.network.NetworkInterfaceCapabilityTrait)
    private static final weave.trait.network.Network.NetworkInterfaceCapabilityTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.network.Network.NetworkInterfaceCapabilityTrait();
    }

    public static weave.trait.network.Network.NetworkInterfaceCapabilityTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkInterfaceCapabilityTrait>
        PARSER = new com.google.protobuf.AbstractParser<NetworkInterfaceCapabilityTrait>() {
      @java.lang.Override
      public NetworkInterfaceCapabilityTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkInterfaceCapabilityTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkInterfaceCapabilityTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkInterfaceCapabilityTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.network.Network.NetworkInterfaceCapabilityTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetworkInterfaceTraitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weave.trait.network.NetworkInterfaceTrait)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isOnline = 1;</code>
     * @return The isOnline.
     */
    boolean getIsOnline();

    /**
     * <code>bytes macAddress = 2;</code>
     * @return The macAddress.
     */
    com.google.protobuf.ByteString getMacAddress();

    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @return A list containing the ipAddresses.
     */
    java.util.List<com.google.protobuf.ByteString> getIpAddressesList();
    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @return The count of ipAddresses.
     */
    int getIpAddressesCount();
    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @param index The index of the element to return.
     * @return The ipAddresses at the given index.
     */
    com.google.protobuf.ByteString getIpAddresses(int index);
  }
  /**
   * Protobuf type {@code weave.trait.network.NetworkInterfaceTrait}
   */
  public static final class NetworkInterfaceTrait extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weave.trait.network.NetworkInterfaceTrait)
      NetworkInterfaceTraitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetworkInterfaceTrait.newBuilder() to construct.
    private NetworkInterfaceTrait(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetworkInterfaceTrait() {
      macAddress_ = com.google.protobuf.ByteString.EMPTY;
      ipAddresses_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NetworkInterfaceTrait();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetworkInterfaceTrait(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isOnline_ = input.readBool();
              break;
            }
            case 18: {

              macAddress_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ipAddresses_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              ipAddresses_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ipAddresses_ = java.util.Collections.unmodifiableList(ipAddresses_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceTrait_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weave.trait.network.Network.NetworkInterfaceTrait.class, weave.trait.network.Network.NetworkInterfaceTrait.Builder.class);
    }

    public static final int ISONLINE_FIELD_NUMBER = 1;
    private boolean isOnline_;
    /**
     * <code>bool isOnline = 1;</code>
     * @return The isOnline.
     */
    @java.lang.Override
    public boolean getIsOnline() {
      return isOnline_;
    }

    public static final int MACADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString macAddress_;
    /**
     * <code>bytes macAddress = 2;</code>
     * @return The macAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMacAddress() {
      return macAddress_;
    }

    public static final int IPADDRESSES_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> ipAddresses_;
    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @return A list containing the ipAddresses.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getIpAddressesList() {
      return ipAddresses_;
    }
    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @return The count of ipAddresses.
     */
    public int getIpAddressesCount() {
      return ipAddresses_.size();
    }
    /**
     * <code>repeated bytes ipAddresses = 3;</code>
     * @param index The index of the element to return.
     * @return The ipAddresses at the given index.
     */
    public com.google.protobuf.ByteString getIpAddresses(int index) {
      return ipAddresses_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isOnline_ != false) {
        output.writeBool(1, isOnline_);
      }
      if (!macAddress_.isEmpty()) {
        output.writeBytes(2, macAddress_);
      }
      for (int i = 0; i < ipAddresses_.size(); i++) {
        output.writeBytes(3, ipAddresses_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isOnline_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isOnline_);
      }
      if (!macAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, macAddress_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ipAddresses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(ipAddresses_.get(i));
        }
        size += dataSize;
        size += 1 * getIpAddressesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weave.trait.network.Network.NetworkInterfaceTrait)) {
        return super.equals(obj);
      }
      weave.trait.network.Network.NetworkInterfaceTrait other = (weave.trait.network.Network.NetworkInterfaceTrait) obj;

      if (getIsOnline()
          != other.getIsOnline()) return false;
      if (!getMacAddress()
          .equals(other.getMacAddress())) return false;
      if (!getIpAddressesList()
          .equals(other.getIpAddressesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsOnline());
      hash = (37 * hash) + MACADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getMacAddress().hashCode();
      if (getIpAddressesCount() > 0) {
        hash = (37 * hash) + IPADDRESSES_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddressesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weave.trait.network.Network.NetworkInterfaceTrait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weave.trait.network.Network.NetworkInterfaceTrait prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weave.trait.network.NetworkInterfaceTrait}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weave.trait.network.NetworkInterfaceTrait)
        weave.trait.network.Network.NetworkInterfaceTraitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceTrait_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weave.trait.network.Network.NetworkInterfaceTrait.class, weave.trait.network.Network.NetworkInterfaceTrait.Builder.class);
      }

      // Construct using weave.trait.network.Network.NetworkInterfaceTrait.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isOnline_ = false;

        macAddress_ = com.google.protobuf.ByteString.EMPTY;

        ipAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return weave.trait.network.Network.internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor;
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceTrait getDefaultInstanceForType() {
        return weave.trait.network.Network.NetworkInterfaceTrait.getDefaultInstance();
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceTrait build() {
        weave.trait.network.Network.NetworkInterfaceTrait result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public weave.trait.network.Network.NetworkInterfaceTrait buildPartial() {
        weave.trait.network.Network.NetworkInterfaceTrait result = new weave.trait.network.Network.NetworkInterfaceTrait(this);
        int from_bitField0_ = bitField0_;
        result.isOnline_ = isOnline_;
        result.macAddress_ = macAddress_;
        if (((bitField0_ & 0x00000001) != 0)) {
          ipAddresses_ = java.util.Collections.unmodifiableList(ipAddresses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ipAddresses_ = ipAddresses_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weave.trait.network.Network.NetworkInterfaceTrait) {
          return mergeFrom((weave.trait.network.Network.NetworkInterfaceTrait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weave.trait.network.Network.NetworkInterfaceTrait other) {
        if (other == weave.trait.network.Network.NetworkInterfaceTrait.getDefaultInstance()) return this;
        if (other.getIsOnline() != false) {
          setIsOnline(other.getIsOnline());
        }
        if (other.getMacAddress() != com.google.protobuf.ByteString.EMPTY) {
          setMacAddress(other.getMacAddress());
        }
        if (!other.ipAddresses_.isEmpty()) {
          if (ipAddresses_.isEmpty()) {
            ipAddresses_ = other.ipAddresses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIpAddressesIsMutable();
            ipAddresses_.addAll(other.ipAddresses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weave.trait.network.Network.NetworkInterfaceTrait parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weave.trait.network.Network.NetworkInterfaceTrait) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isOnline_ ;
      /**
       * <code>bool isOnline = 1;</code>
       * @return The isOnline.
       */
      @java.lang.Override
      public boolean getIsOnline() {
        return isOnline_;
      }
      /**
       * <code>bool isOnline = 1;</code>
       * @param value The isOnline to set.
       * @return This builder for chaining.
       */
      public Builder setIsOnline(boolean value) {
        
        isOnline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isOnline = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOnline() {
        
        isOnline_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString macAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes macAddress = 2;</code>
       * @return The macAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMacAddress() {
        return macAddress_;
      }
      /**
       * <code>bytes macAddress = 2;</code>
       * @param value The macAddress to set.
       * @return This builder for chaining.
       */
      public Builder setMacAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes macAddress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMacAddress() {
        
        macAddress_ = getDefaultInstance().getMacAddress();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> ipAddresses_ = java.util.Collections.emptyList();
      private void ensureIpAddressesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ipAddresses_ = new java.util.ArrayList<com.google.protobuf.ByteString>(ipAddresses_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @return A list containing the ipAddresses.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getIpAddressesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(ipAddresses_) : ipAddresses_;
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @return The count of ipAddresses.
       */
      public int getIpAddressesCount() {
        return ipAddresses_.size();
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @param index The index of the element to return.
       * @return The ipAddresses at the given index.
       */
      public com.google.protobuf.ByteString getIpAddresses(int index) {
        return ipAddresses_.get(index);
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @param index The index to set the value at.
       * @param value The ipAddresses to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddresses(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIpAddressesIsMutable();
        ipAddresses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @param value The ipAddresses to add.
       * @return This builder for chaining.
       */
      public Builder addIpAddresses(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIpAddressesIsMutable();
        ipAddresses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @param values The ipAddresses to add.
       * @return This builder for chaining.
       */
      public Builder addAllIpAddresses(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureIpAddressesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ipAddresses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ipAddresses = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddresses() {
        ipAddresses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:weave.trait.network.NetworkInterfaceTrait)
    }

    // @@protoc_insertion_point(class_scope:weave.trait.network.NetworkInterfaceTrait)
    private static final weave.trait.network.Network.NetworkInterfaceTrait DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weave.trait.network.Network.NetworkInterfaceTrait();
    }

    public static weave.trait.network.Network.NetworkInterfaceTrait getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkInterfaceTrait>
        PARSER = new com.google.protobuf.AbstractParser<NetworkInterfaceTrait>() {
      @java.lang.Override
      public NetworkInterfaceTrait parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetworkInterfaceTrait(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetworkInterfaceTrait> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkInterfaceTrait> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public weave.trait.network.Network.NetworkInterfaceTrait getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weave_trait_network_NetworkInterfaceTrait_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031weave/trait/network.proto\022\023weave.trait" +
      ".network\032\022weave/common.proto\"\373\002\n\037Network" +
      "InterfaceCapabilityTrait\022W\n\004type\030\001 \001(\0162I" +
      ".weave.trait.network.NetworkInterfaceCap" +
      "abilityTrait.NetworkInterfaceType\022,\n\013des" +
      "cription\030\002 \001(\0132\027.weave.common.StringRef\"" +
      "\320\001\n\024NetworkInterfaceType\022&\n\"NETWORK_INTE" +
      "RFACE_TYPE_UNSPECIFIED\020\000\022\'\n#NETWORK_INTE" +
      "RFACE_TYPE_WEAVE_TUNNEL\020\001\022\037\n\033NETWORK_INT" +
      "ERFACE_TYPE_WIFI\020\002\022!\n\035NETWORK_INTERFACE_" +
      "TYPE_THREAD\020\003\022#\n\037NETWORK_INTERFACE_TYPE_" +
      "CELLULAR\020\004\"R\n\025NetworkInterfaceTrait\022\020\n\010i" +
      "sOnline\030\001 \001(\010\022\022\n\nmacAddress\030\002 \001(\014\022\023\n\013ipA" +
      "ddresses\030\003 \003(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          weave.common.Common.getDescriptor(),
        });
    internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_network_NetworkInterfaceCapabilityTrait_descriptor,
        new java.lang.String[] { "Type", "Description", });
    internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weave_trait_network_NetworkInterfaceTrait_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weave_trait_network_NetworkInterfaceTrait_descriptor,
        new java.lang.String[] { "IsOnline", "MacAddress", "IpAddresses", });
    weave.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
